//  Copyright © 2017 Arc676/Alessandro Vinciguerra. All rights reserved.
//  Text in just this file available under Wikipedia's Creative Commons License
//  (Text of Creative Commons Attribution-ShareAlike 3.0 Unported License).

//Sources
//https://en.wikipedia.org/w/index.php?title=Vehicle_registration_plates_of_China
//https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Italy
//https://de.wikipedia.org/wiki/Diplomatenkennzeichen_(Deutschland)
//https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Switzerland
//https://de.wikipedia.org/wiki/Liste_der_Kfz-Kennzeichen_in_Deutschland
//https://en.wikipedia.org/wiki/Departments_of_France

var searchItems = [
            [
                "101 - Afghanistan",
                "102 - Albania",
                "103 - Algeria",
                "104 - Angola",
                "105 - Argentina",
                "106 - Australia",
                "107 - Austria",
                "108 - Azerbaijan",
                "109 - Bahrain",
                "110 - Bangladesh",
                "111 - Belarus",
                "112 - Belgium",
                "113 - Benin",
                "114 - Bolivia",
                "115 - Botswana",
                "116 - Brazil",
                "117 - Brunei",
                "118 - Bulgaria",
                "119 - Burkina Faso",
                "120 - Burundi",
                "121 - Cambodia",
                "122 - Cameroon",
                "123 - Canada",
                "124 - Chad",
                "125 - Chile",
                "126 - Colombia",
                "127 - Congo",
                "128 - Ivory Coast",
                "129 - Croatia",
                "130 - Cuba",
                "131 - Cyprus",
                "132 - Czech Rep.",
                "133 - N. Korea",
                "134 - Denmark",
                "135 - E. Timor",
                "136 - Ecuador",
                "137 - Egypt",
                "138 - Equatorial Guinea",
                "139 - Eritrea",
                "140 - Ethiopia",
                "141 - Fiji",
                "142 - Finland",
                "143 - France",
                "144 - Gabon",
                "145 - Germany",
                "146 - Ghana",
                "147 - Greece",
                "148 - Guinea",
                "149 - Guyana",
                "150 - Hungary",
                "151 - Iceland",
                "152 - India",
                "153 - Indonesia",
                "154 - Iran",
                "155 - Iraq",
                "156 - Ireland",
                "157 - Israel",
                "158 - Italy",
                "160 - Jordan",
                "161 - Kazakhstan",
                "162 - Kenya",
                "163 - Kiribati",
                "164 - Kuwait",
                "165 - Kyrgyzstan",
                "166 - Laos",
                "167 - Lebanon",
                "168 - Libya",
                "169 - Luxembourg",
                "170 - Madagascar",
                "171 - Malaysia",
                "172 - Mali",
                "173 - Malta",
                "174 - Marshall Islands",
                "175 - Mauritania",
                "176 - Mexico",
                "177 - Micronesia",
                "178 - Mongolia",
                "179 - Morocco",
                "180 - Mozambique",
                "181 - Myanmar",
                "182 - Nepal",
                "183 - Netherlands",
                "184 - New Zealand",
                "185 - Nigeria",
                "186 - Norway",
                "187 - Oman",
                "188 - Pakistan",
                "189 - Palestine",
                "190 - Papua New Guinea",
                "191 - Peru",
                "192 - Philippines",
                "193 - Poland",
                "194 - Portugal",
                "195 - Qatar",
                "196 - S. Korea",
                "197 - Romania",
                "198 - Russia",
                "199 - Rwanda",
                "200 - Saudi Arabia",
                "201 - Senegal",
                "202 - Seychelles",
                "203 - Sierra Leone",
                "204 - Singapore",
                "205 - Slovakia",
                "206 - Slovenia",
                "207 - Somalia",
                "208 - S. Africa",
                "209 - Spain",
                "210 - Sri Lanka",
                "211 - Sudan",
                "212 - Sweden",
                "213 - Switzerland",
                "214 - Syria",
                "215 - Tanzania",
                "216 - Thailand",
                "217 - Toga",
                "218 - Tunisia",
                "219 - Turkey",
                "220 - Uganda",
                "221 - Ukraine",
                "222 - UAE",
                "223 - UK",
                "224 - US",
                "225 - Uruguay",
                "226 - Vanuatu",
                "227 - Venezuela",
                "228 - Vietnam",
                "229 - Yemen",
                "230 - Serbia",
                "231 - Democratic Rep. of Congo",
                "232 - Zambia",
                "233 - Zimbabwe",
                "234 - Macedonia",
                "235 - Japan",
                "236 - Lesotho",
                "237 - Uzbekistan",
                "238 - Turkmenistan",
                "239 - Georgia",
                "240 - Namibia",
                "241 - Lithuania",
                "242 - Moldova",
                "243 - Mauritius",
                "244 - Panama",
                "245 - Niger",
                "246 - Tajikistan",
                "247 - Antigua and Barbuda",
                "248 - Armenia",
                "249 - Suriname",
                "251 - Estonia",
                "252 - Haiti",
                "253 - Latvia",
                "254 - Bosnia and Herzegovina",
                "255 - Guinea-Bissau",
                "256 - Cape Verde",
                "257 - Djibouti",
                "258 - Central African Rep.",
                "260 - Dominica",
                "261 - Liberia",
                "262 - Jamaica",
                "263 - Grenada",
                "264 - Maldives",
                "265 - Costa Rica",
                "266 - Malawi",
                "267 - Bahamas",
                "268 - Comoros",
                "269 - Montenegro",
                "270 - Tonga",
                "271 - S. Sudan",
                "272 - Barbados",
                "159 - Shanghai Cooperation Organisation",
                "259 - Pacific Islands Forum",
                "300 - EU",
                "301 - Arab League",
                "302 - UN Development Program",
                "303 - UN Food and Agriculture Organization",
                "304 - UN Population Fund",
                "305 - UN World Food Programme",
                "306 - UN Children's Fund",
                "307 - UN World Health Organization",
                "308 - UN Educational, Scientific and Cultural Organization",
                "309 - UN International Labour Organization",
                "310 - World Bank",
                "311 - UN High Commissioner for Refugees",
                "313 - International Monetary Fund",
                "314 - International Finance Corporation",
                "316 - UN Industrial Development Organization",
                "317 - Asia Development Bank",
                "318 - Red Cross",
                "319 - UN Asian and Pacific Centre for Agricultural Engineering and Machinery",
                "321 - UN Environment Programme"
            ],
            [
                "皖 - Anhui",
                "皖A - Hefei",
                "皖B - Wuhu",
                "皖C - Bengbu",
                "皖D - Huainan",
                "皖E - Ma'anshan",
                "皖F - Huaibei",
                "皖G - Tongling",
                "皖H - Anqing",
                "皖J - Huangshan",
                "皖K - Fuyang",
                "皖L - Suzhou",
                "皖M - Chuzhou",
                "皖N - Lu'an",
                "皖P - Xuancheng",
                "皖Q - Chaohu",
                "皖R - Chizhou",
                "皖S - Bozhou",
                "闽 - Fujian",
                "闽A - Fuzhou",
                "闽B - Putian",
                "闽C - Quanzhou",
                "闽D - Xiamen",
                "闽E - Zhangzhou",
                "闽F - Longyan",
                "闽G - Sanming",
                "闽H - Nanping",
                "闽J - Ningde",
                "闽K - Provincial-level agencies",
                "闽O - Police vehicles",
                "甘 - Gansu",
                "甘A - Lanzhou",
                "甘B - Jiayuguan",
                "甘C - Jinchang",
                "甘D - Baiyin",
                "甘E - Tianshui",
                "甘F - Jiuquan",
                "甘G - Zhangye",
                "甘H - Wuwei",
                "甘J - Dingxi",
                "甘K - Longnan",
                "甘L - Pingliang",
                "甘M - Qingyang",
                "甘N - Linxia Hui Autonomous Prefecture",
                "甘P - Gannan Tibetan Autonomous Prefecture",
                "粤 - Guangdong",
                "粤A - Guangzhou",
                "粤AQ - Panyu",
                "粤B - Shenzhen",
                "粤C - Zhuhai",
                "粤D - Shantou",
                "粤E - Foshan",
                "粤EV - Gaoming",
                "粤ET - Sanshui",
                "粤F - Shaoguan",
                "粤G - Zhanjiang",
                "粤H - Zhaoqing & Gaoyao",
                "粤HL - Sihui",
                "粤J - Jiangmen",
                "粤K - Maoming",
                "粤L - Huizhou",
                "粤M - Meizhou",
                "粤N - Shanwei",
                "粤O - Guangdong Provincial Public Security Department",
                "粤P - Heyuan",
                "粤Q - Yangjiang",
                "粤R - Qingyuan",
                "粤S - Dongguan",
                "粤T - Zhongshan",
                "粤U - Chaozhou",
                "粤V - Jieyang",
                "粤W - Yunfu",
                "粤X - Shunde",
                "粤Y - Nanhai",
                "粤Z - Hong Kong & Macau",
                "贵 - Guizhou",
                "贵A - Guiyang",
                "贵B - Liupanshui",
                "贵C - Zunyi",
                "贵D - Tongren",
                "贵E - Qianxinan",
                "贵F - Bijie",
                "贵G - Anshun",
                "贵H - Qiandonnan",
                "贵J - Qiannan",
                "琼 - Hainan",
                "琼A - Haikou",
                "琼B - Sanya",
                "琼C - Qiongbei",
                "琼D - Dongfang",
                "冀 - Hebei",
                "冀A - Shijiazhuang",
                "冀B - Tangshan",
                "冀C - Qinhuangdao",
                "冀D - Handan",
                "冀E - Xingtai",
                "冀F - Baoding",
                "冀G - Zhangjiakou",
                "冀H - Chengde",
                "冀J - Cangzhou",
                "冀R - Langfang",
                "冀T - Hengshui",
                "黑 - Heilongjiang",
                "黑A - Harbin",
                "黑B - Qiqihar",
                "黑C - Mudanjiang",
                "黑D - Jiamusi",
                "黑E - Daqing",
                "黑F - Yichun",
                "黑G - Jixi",
                "黑H - Hegang",
                "黑J - Shuangyashan",
                "黑K - Qitaihe",
                "黑L - Area of the Sungari River",
                "黑M - Suihua",
                "黑N - Heihe",
                "黑P - Daxing'anling Prefecture",
                "豫 - Henan",
                "豫A - Zhengzhou",
                "豫B - Kaifeng",
                "豫C - Luoyang",
                "豫D - Pingdingshan",
                "豫E - Anyang",
                "豫F - Hebi",
                "豫G - Xinxiang",
                "豫H - Jiaozuo",
                "豫J - Puyang",
                "豫K - Xuchang",
                "豫L - Luohe",
                "豫M - Sanmenxia",
                "豫N - Shangqiu",
                "豫P - Zhoukou",
                "豫Q - Zhumadian",
                "豫R - Nanyang",
                "豫S - Xinyang",
                "豫U - Jiyuan",
                "鄂 - Hubei",
                "鄂A - Wuhan",
                "鄂B - Huangshi",
                "鄂C - Shiyan",
                "鄂D - Jingzhou",
                "鄂E - Yichang",
                "鄂F - Xiangfan",
                "鄂G - Ezhou",
                "鄂H - Jingmen",
                "鄂J - Huanggang",
                "鄂K - Xiaogan",
                "鄂L - Xianning",
                "鄂M - Xiantao",
                "鄂N - Qianjiang",
                "鄂P - Shennongjia",
                "鄂Q - Enshi Tujia and Miao Autonomous Prefecture",
                "鄂R - Tianmen",
                "鄂S - Suizhou",
                "湘 - Hunan",
                "湘A - Changsha",
                "湘B - Zhuzhou",
                "湘C - Xiangtan",
                "湘D - Hengyang",
                "湘E - Shaoyang",
                "湘F - Yueyang",
                "湘G - Zhangjiajie",
                "湘H - Yiyang",
                "湘J - Changde",
                "湘K - Loudi",
                "湘L - Chenzhou",
                "湘M - Yongzhou",
                "湘N - Huaihua",
                "湘P - Xiangxi Tujia and Miao Autonomous Prefecture",
                "苏 - Jiangsu",
                "苏A - Nanjing",
                "苏B - Wuxi",
                "苏C - Xuzhou",
                "苏D - Changzhou",
                "苏E - Suzhou",
                "苏F - Nantong",
                "苏G - Lianyungang",
                "苏H - Huai'an",
                "苏J - Yancheng",
                "苏K - Yangzhou",
                "苏L - Zhenjiang",
                "苏M - Taizhou",
                "苏N - Suqian",
                "赣 - Jiangxi",
                "赣A - Nanchang",
                "赣B - Ganzhou",
                "赣C - Yichun",
                "赣D - Ji'an",
                "赣E - Shangrao",
                "赣F - Fuzhou",
                "赣G - Jiujiang",
                "赣H - Jingdezhen",
                "赣J - Pingxiang",
                "赣K - Xinyu",
                "赣L - Yingtan",
                "吉 - Jilin",
                "吉A - Changchun",
                "吉B - Jilin City",
                "吉C - Siping",
                "吉D - Liaoyuan",
                "吉E - Tonghua",
                "吉F - Baishan",
                "吉G - Baicheng",
                "吉H - Yanbian Korean Autonomous Prefecture",
                "吉J - Songyuan",
                "辽 - Liaoning",
                "辽A - Shenyang",
                "辽B - Dalian",
                "辽C - Anshan",
                "辽D - Fushun",
                "辽E - Benxi",
                "辽F - Dandong",
                "辽G - Jinzhou",
                "辽H - Yingkou",
                "辽J - Fuxin",
                "辽K - Liaoyang",
                "辽L - Panjin",
                "辽M - Tieling",
                "辽N - Chaoyang",
                "辽O - Police Vehicles",
                "辽P - Huludao",
                "青 - Qinghai",
                "青A - Xining",
                "青B - Haidong",
                "青C - Haibei Tibetan Autonomous Prefecture",
                "青D - Huangnan Tibetan Autonomous Prefecture",
                "青E - Hainan Tibetan Autonomous Prefecture",
                "青F - Golog Tibetan Autonomous Prefecture",
                "青G - Gyêgu Tibetan Autonomous Prefecture",
                "青H - Haixi Mongol and Tibetan Autonomous Prefecture",
                "陕 - Shaanxi",
                "陕A - Xi'an",
                "陕AV - Provincial-level agencies",
                "陕B - Tongchuan",
                "陕C - Baoji",
                "陕D - Xianyang",
                "陕E - Weinan",
                "陕F - Hanzhong",
                "陕G - Ankang",
                "陕H - Shangluo",
                "陕J - Yan'an",
                "陕K - Yulin",
                "陕V - Yangling Gaoxin Agricultural Zone",
                "鲁 - Shandong",
                "鲁A - Jinan",
                "鲁B - Qingdao",
                "鲁C - Zibo",
                "鲁D - Zaozhuang",
                "鲁E - Dongying",
                "鲁F - Yantai",
                "鲁G - Weifang",
                "鲁H - Jining",
                "鲁J - Tai'an",
                "鲁K - Weihai",
                "鲁L - Rizhao",
                "鲁M - Binzhou",
                "鲁N - Dezhou",
                "鲁O - Local government",
                "鲁P - Liaocheng",
                "鲁Q - Linyi",
                "鲁R - Heze",
                "鲁S - Laiwu",
                "鲁U - Qingdao Extra",
                "鲁V - Weifang Extra",
                "鲁W - Jinan Extra",
                "晋 - Shanxi",
                "晋A - Taiyuan",
                "晋B - Datong",
                "晋C - Yangquan",
                "晋D - Changzhi",
                "晋E - Jincheng",
                "晋F - Shuozhou",
                "晋H - Xinzhou",
                "晋J - Lüliang",
                "晋K - Jinzhong",
                "晋L - Linfen",
                "晋M - Yuncheng",
                "川 - Sichuan",
                "川A - Chengdu",
                "川B - Mianyang",
                "川C - Zigong",
                "川D - Panzhihua",
                "川E - Luzhou",
                "川F - Deyang",
                "川H - Guangyuan",
                "川J - Suining",
                "川K - Neijiang",
                "川L - Leshan",
                "川M - Ziyang",
                "川Q - Yibin",
                "川R - Nanchong",
                "川S - Dazhou",
                "川T - Ya'an",
                "川U - Ngawa Tibetan and Qiang Autonomous Prefecture",
                "川V - Garzê Tibetan Autonomous Prefecture",
                "川W - Liangshan Yi Autonomous Prefecture",
                "川X - Guang'an",
                "川Y - Bazhong",
                "川Z - Meishan",
                "云 - Yunnan",
                "云A - Kunming",
                "云C - Zhaotong",
                "云D - Qujing",
                "云E - Chuxiong Yi Autonomous Prefecture",
                "云F - Yuxi",
                "云G - Honghe Hani and Yi Autonomous Prefecture",
                "云H - Wenshan Zhuang and Miao Autonomous Prefecture",
                "云J - Pu'er",
                "云K - Xishuangbanna Dai Autonomous Prefecture",
                "云L - Dali Bai Autonomous Prefecture",
                "云M - Baoshan",
                "云N - Dehong Dai and Jingpo Autonomous Prefecture",
                "云P - Lijiang",
                "云Q - Nujiang Lisu Autonomous Prefecture",
                "云R - Diqing Tibetan Autonomous Prefecture",
                "云S - Lincang",
                "浙 - Zhejiang",
                "浙A - Hangzhou",
                "浙B - Ningbo",
                "浙C - Wenzhou",
                "浙D - Shaoxing",
                "浙E - Huzhou",
                "浙F - Jiaxing",
                "浙G - Jinhua",
                "浙H - Quzhou",
                "浙J - Taizhou",
                "浙K - Lishui",
                "浙L - Zhoushan",
                "浙O - Foreign enterprises",
                "桂 - Guangxi",
                "桂A - Nanning",
                "桂B - Liuzhou",
                "桂C - Guilin",
                "桂D - Wuzhou",
                "桂E - Beihai",
                "桂F - Chongzuo",
                "桂G - Laibin",
                "桂H - Guilin",
                "桂J - Hezhou",
                "桂K - Yulin",
                "桂L - Baise",
                "桂M - Hechi",
                "桂N - Qinzhou",
                "桂P - Fangchenggang",
                "桂R - Guigang",
                "蒙 - Inner Mongolia",
                "蒙A - Hohhot",
                "蒙B - Baotou",
                "蒙C - Wuhai",
                "蒙D - Chifeng",
                "蒙E - Hulunbuir",
                "蒙F - Hinggan League",
                "蒙G - Tongliao",
                "蒙H - Xilin Gol League",
                "蒙J - Ulaan Chab",
                "蒙K - Ordos",
                "蒙L - Bayan Nur",
                "蒙M - Alxa League",
                "宁 - Ningxia",
                "宁A - Yinchuan",
                "宁B - Shizuishan",
                "宁C - Wuzhong",
                "宁D - Guyuan",
                "宁E - Zhongwei",
                "藏 - Tibet",
                "藏A - Lhasa",
                "藏B - Qamdo",
                "藏C - Shannan Prefecture",
                "藏D - Xigazê",
                "藏E - Naqu Prefecture",
                "藏F - Ngari Prefecture",
                "藏G - Nyingchi",
                "新 - Xinjiang",
                "新A - Ürümqi",
                "新B - Changji Hui Autonomous Prefecture",
                "新C - Shihezi",
                "新D - Kuitun",
                "新E - Börtala Mongol Autonomous Prefecture",
                "新F - Ili Kazakh Autonomous Prefecture",
                "新G - Qoqek",
                "新H - Altay",
                "新J - Karamay",
                "新K - Turpan",
                "新L - Hami",
                "新M - Bayin'gholin Mongol Autonomous Prefecture",
                "新N - Aksu Prefecture",
                "新P - Kizilsu Kirghiz Autonomous Prefecture",
                "新Q - Kashgar",
                "新R - Hotan"
            ],
            [
                "AG - Agrigento",
                "AQ - L'Aquila",
                "BG - Bergamo",
                "BR - Brindisi",
                "CB - Campobasso",
                "CN - Cuneo",
                "CZ - Catanzaro",
                "FI - Firenze",
                "GR - Grosseto",
                "LE - Lecce",
                "MB - Monza e Brianza",
                "MO - Modena",
                "NU - Nuoro",
                "PC - Piacenza",
                "PN - Pordenone",
                "PV - Pavia",
                "RG - Ragusa",
                "SA - Salerno",
                "SS - Sassari",
                "TO - Torino",
                "UD - Udine",
                "VI - Vicenza",
                "AL - Alessandria",
                "AR - Arezzo",
                "BI - Biella",
                "BS - Brescia",
                "CE - Caserta",
                "CO - Como",
                "EN - Enna",
                "FM - Fermo",
                "IM - Imperia",
                "LI - Livorno",
                "MC - Macerata",
                "MS - Massa-Carrara",
                "OG - Ogliastra",
                "PD - Padova",
                "PO - Prato",
                "PZ - Potenza",
                "RI - Rieti",
                "SI - Siena",
                "SV - Savona",
                "TP - Trapani",
                "VA - Varese",
                "VR - Verona",
                "AP - Ascoli Piceno",
                "BA - Bari",
                "BO - Bologna",
                "CA - Cagliari",
                "CL - Caltanissetta",
                "CT - Catania",
                "FG - Foggia",
                "GO - Gorizia",
                "LC - Lecco",
                "LU - Lucca",
                "MN - Mantova",
                "NO - Novara",
                "PA - Palermo",
                "PI - Pisa",
                "PU - Pesaro-Urbino",
                "RE - Reggio Emilia",
                "Roma - Roma",
                "SR - Siracusa",
                "TN - Trento",
                "TV - Treviso",
                "VE - Venezia",
                "VV - Vibo Valentia",
                "AO - Aosta",
                "AV - Avellino",
                "BN - Benevento",
                "BZ - Bolzano",
                "CI - Carbonia-Iglesias",
                "CS - Cosenza",
                "FE - Ferrara",
                "GE - Genova",
                "KR - Crotone",
                "LT - Latina",
                "MI - Milano",
                "NA - Napoli",
                "OT - Olbia-Tempio",
                "PG - Perugia",
                "PT - Pistoia",
                "RC - Reggio Calabria",
                "RO - Rovigo",
                "SP - La Spezia",
                "TE - Teramo",
                "TS - Trieste",
                "VC - Vercelli",
                "VT - Viterbo",
                "AN - Ancona",
                "AT - Asti",
                "BL - Belluno",
                "BT - Barletta-Andria-Trani",
                "CH - Chieti",
                "CR - Cremona",
                "FC - Forlì-Cesena",
                "FR - Frosinone",
                "IS - Isernia",
                "LO - Lodi",
                "ME - Messina",
                "MT - Matera",
                "OR - Oristano",
                "PE - Pescara",
                "PR - Parma",
                "RA - Ravenna",
                "RN - Rimini",
                "SO - Sondrio",
                "TA - Taranto",
                "TR - Terni",
                "VB - Verbania",
                "VS - Medio Campidano"
            ],
            [
                "0-1 - Bundespräsident",
                "0-2 - Bundeskanzler",
                "0-3 - Außenminister",
                "0-4 - Erster Staatssekretär im Auswärtigen Amt",
                "1-1 - Bundestagspräsident",
                "10 - Vatikanstadt",
                "11 - Ägypten",
                "12 - Angola",
                "13 - Albanien",
                "14 - Äthiopien",
                "15 - Afghanistan",
                "16 - Algerien",
                "17 - Vereinigte Staaten",
                "18 - Argentinien",
                "19 - Australien",
                "20 - Bangladesch",
                "21 - Belgien",
                "22 - Brunei",
                "23 - Bulgarien",
                "24 - Myanmar",
                "25 - Bolivien",
                "26 - Brasilien",
                "27 - Burundi",
                "28 - Chile",
                "29 - Volksrepublik China",
                "30 - Costa Rica",
                "31 - Weißrussland",
                "32 - Bosnien und Herzegowina",
                "33 - Äquatorialguinea",
                "34 - Dänemark",
                "35 - Benin",
                "36 - Dominikanische Republik",
                "37 - Ecuador",
                "38 - Elfenbeinküste",
                "39 - El Salvador",
                "40 - Kosovo",
                "41 - Estland",
                "42 - Liechtenstein",
                "43 - Montenegro",
                "44 - Finnland",
                "45 - Frankreich",
                "46 - Gabun",
                "47 - Ghana",
                "48 - Griechenland",
                "49 - Vereinigtes Königreich",
                "50 - Guatemala",
                "51 - Guinea",
                "52 - Lettland",
                "53 - Litauen",
                "54 - Haiti",
                "55 - Honduras",
                "56 - Indien",
                "57 - Indonesien",
                "58 - Irak",
                "59 - Iran",
                "60 - Irland",
                "61 - Island",
                "62 - Laos",
                "63 - Kap Verde",
                "64 - Israel",
                "65 - Italien",
                "66 - Jamaika",
                "67 - Japan",
                "68 - Jemen",
                "69 - Jordanien",
                "70 - Serbien",
                "71 - Kuwait",
                "72 - Kuba",
                "73 - Katar",
                "74 - Kamerun",
                "75 - Kanada",
                "76 - Kenia",
                "77 - Kolumbien",
                "78 - Republik Kongo",
                "79 - Südkorea",
                "80 - Libanon",
                "81 - Liberia",
                "82 - Libyen",
                "83 - Lesotho",
                "84 - Luxemburg",
                "85 - Madagaskar",
                "86 - Malawi",
                "87 - Malaysia",
                "88 - Mali",
                "89 - Marokko",
                "90 - Mauretanien",
                "91 - Mexiko",
                "92 - Malta",
                "93 - Monaco",
                "94 - Nepal",
                "95 - Neuseeland",
                "96 - Nicaragua",
                "97 - Niederlande",
                "98 - Niger",
                "99 - Nigeria",
                "100 - Norwegen",
                "101 - Mongolei",
                "102 - Mosambik",
                "103 - Oman",
                "104 - Burkina Faso",
                "105 - Österreich",
                "106 - Pakistan",
                "107 - Panama",
                "108 - Paraguay",
                "109 - Peru",
                "110 - Philippinen",
                "111 - Polen",
                "112 - Portugal",
                "113 - Papua-Neuguinea",
                "114 - Namibia",
                "115 - Ruanda",
                "116 - Rumänien",
                "117 - Sambia",
                "118 - Saudi-Arabien",
                "119 - Schweden",
                "120 - Schweiz",
                "121 - Senegal",
                "122 - Sierra Leone",
                "123 - Singapur",
                "124 - Simbabwe",
                "125 - Somalia",
                "126 - Spanien",
                "127 - Sri Lanka",
                "128 - Sudan",
                "129 - Südafrika",
                "130 - Syrien",
                "131 - Tansania",
                "132 - Thailand",
                "133 - Togo",
                "134 - Tonga",
                "135 - Tschechien",
                "136 - Tschad",
                "137 - Türkei",
                "138 - Tunesien",
                "139 - Uganda",
                "140 - Russland",
                "141 - Uruguay",
                "142 - Ungarn",
                "143 - Ukraine",
                "144 - Grenada",
                "146 - Venezuela",
                "147 - Vietnam",
                "148 - Vereinigte Arabische Emirate",
                "151 - Demokratische Republik Kongo",
                "152 - Zentralafrikanische Republik",
                "153 - Zypern",
                "154 - Kroatien",
                "155 - Slowenien",
                "156 - Aserbaidschan",
                "157 - Slowakei",
                "158 - Kasachstan",
                "159 - Mazedonien",
                "160 - Usbekistan",
                "161 - Eritrea",
                "162 - Georgien",
                "163 - Tadschikistan",
                "164 - Bahrain",
                "165 - Kambodscha",
                "166 - Armenien",
                "167 - Kirgisistan",
                "168 - Moldawien",
                "169 - Turkmenistan",
                "200 - Mauritius",
                "201 - Nordkorea",
                "202 - Dschibuti",
                "203 - Guinea-Bissau",
                "204 - Südsudan",
                "205 - Botswana"
            ],
            [
                "A - Stadt/Landkreis Augsburg; Polizeipräsidium Schwaben Nord",
                "AA - Ostalbkreis",
                "AB - Stadt/Landkreis Aschaffenburg",
                "ABG - Landkreis Altenburger Land",
                "ABI - Landkreis Anhalt-Bitterfeld",
                "AC - Städteregion Aachen",
                "AE - Vogtlandkreis",
                "AH - Kreis Borken",
                "AIB - Landkreis München/Rosenheim",
                "AIC - Landkreis Aichach-Friedberg",
                "AK - Landkreis Altenkirchen (Westerwald)",
                "ALF - Landkreis Hildesheim",
                "ALZ - Landkreis Aschaffenburg",
                "AM - Stadt Amberg",
                "AN - Stadt/Landkreis Ansbach",
                "ANA - Erzgebirgskreis",
                "ANG - Landkreis Uckermark",
                "ANK - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
                "AÖ - Landkreis Altötting",
                "AP - Landkreis Weimarer Land",
                "APD - Landkreis Weimarer Land",
                "ARN - Ilm-Kreis",
                "ART - Kyffhäuserkreis",
                "AS - Landkreis Amberg-Sulzbach",
                "ASL - Salzlandkreis",
                "ASZ - Erzgebirgskreis",
                "AT - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "AU - Erzgebirgskreis",
                "AUR - Landkreis Aurich",
                "AW - Landkreis Ahrweiler",
                "AZ - Landkreis Alzey-Worms",
                "AZE - Landkreis Anhalt-Bitterfeld",
                "B - Stadt Berlin; Senat, Abgeordnetenhaus, Diplomaten",
                "BA - Stadt/Landkreis Bamberg; Bayerisches Bereitschaftspolizeipräsidium",
                "BAD - Stadt Baden-Baden",
                "BAR - Landkreis Barnim",
                "BB - Landkreis Böblingen",
                "BBG - Salzlandkreis",
                "BBL - Brandenburg, Landesregierung, Landtag, Polizei",
                "BC - Landkreis Biberach",
                "BCH - Neckar-Odenwald-Kreis",
                "BD - Deutscher Bundestag, Bundesrat, Bundespräsidialamt, Bundesregierung, Bundesministerien, Bundesfinanzverwaltung, Bundesverfassungsgericht",
                "BE - Kreis Warendorf",
                "BED - Landkreis Mittelsachsen",
                "BER - Landkreis Barnim",
                "BF - Kreis Steinfurt",
                "BGD - Landkreis Berchtesgadener Land",
                "BGL - Landkreis Berchtesgadener Land",
                "BH - Ortenaukreis; Landkreis Rastatt",
                "BI - Stadt Bielefeld",
                "BID - Landkreis Marburg-Biedenkopf",
                "BIN - Landkreis Mainz-Bingen",
                "BIR - Landkreis Birkenfeld",
                "BIT - Eifelkreis Bitburg-Prüm",
                "BIW - Landkreis Bautzen",
                "BK - Rems-Murr-Kreis; Landkreis Börde",
                "BKS - Landkreis Bernkastel-Wittlich",
                "BL - Zollernalbkreis",
                "BLB - Kreis Siegen-Wittgenstein",
                "BLK - Burgenlandkreis",
                "BM - Rhein-Erft-Kreis",
                "BN - Stadt Bonn; Diplomaten",
                "BNA - Landkreis Leipzig",
                "BO - Stadt Bochum",
                "BÖ - Landkreis Börde",
                "BOH - Kreis Borken",
                "BOR - Kreis Borken",
                "BOT - Stadt Bottrop",
                "BP - Bundespolizei",
                "BRA - Landkreis Wesermarsch",
                "BRB - Stadt Brandenburg an der Havel",
                "BRG - Landkreis Jerichower Land",
                "BRK - Landkreis Bad Kissingen",
                "BRL - Landkreis Goslar",
                "BRV - Landkreis Rotenburg (Wümme)",
                "BS - Stadt/Polizeidirektion Braunschweig",
                "BT - Stadt/Landkreis Bayreuth; Polizeipräsidium Oberfranken",
                "BTF - Landkreis Anhalt-Bitterfeld",
                "BÜD - Wetteraukreis",
                "BUL - Landkreis Amberg-Sulzbach/Schwandorf",
                "BÜR - Kreis Paderborn",
                "BÜS - Gemeinde Büsingen am Hochrhein",
                "BÜZ - Landkreis Rostock",
                "BW - Wasserstraßen- und Schifffahrtsverwaltung des Bundes",
                "BWL - Baden-Württemberg, Landesregierung, Landtag, Polizei",
                "BYL - Bayern, Landesregierung, Landtag",
                "BZ - Landkreis Bautzen",
                "C - Stadt Chemnitz",
                "CA - Landkreis Oberspreewald-Lausitz",
                "CAS - Kreis Recklinghausen",
                "CB - Stadt Cottbus",
                "CE - Landkreis Celle",
                "CHA - Landkreis Cham",
                "CLP - Landkreis Cloppenburg",
                "CLZ - Landkreis Goslar",
                "CO - Stadt/Landkreis Coburg",
                "COC - Landkreis Cochem-Zell",
                "COE - Kreis Coesfeld",
                "CR - Landkreis Schwäbisch Hall",
                "CUX - Landkreis Cuxhaven",
                "CW - Landkreis Calw",
                "D - Stadt Düsseldorf",
                "DA - Landkreis Darmstadt-Dieburg; Stadt Darmstadt",
                "DAH - Landkreis Dachau",
                "DAN - Landkreis Lüchow-Dannenberg",
                "DAU - Landkreis Vulkaneifel",
                "DBR - Landkreis Rostock",
                "DD - Stadt Dresden; Polizei Sachsen",
                "DE - Stadt Dessau-Roßlau",
                "DEG - Landkreis Deggendorf",
                "DEL - Stadt Delmenhorst",
                "DGF - Landkreis Dingolfing-Landau",
                "DH - Landkreis Diepholz",
                "DI - Landkreis Darmstadt-Dieburg",
                "DIL - Lahn-Dill-Kreis ohne die Stadt Wetzlar",
                "DIN - Kreis Wesel",
                "DIZ - Rhein-Lahn-Kreis",
                "DKB - Landkreis Ansbach",
                "DL - Landkreis Mittelsachsen",
                "DLG - Landkreis Dillingen an der Donau",
                "DM - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "DN - Kreis Düren",
                "DO - Stadt Dortmund",
                "DON - Landkreis Donau-Ries",
                "DU - Stadt Duisburg",
                "DUD - Landkreis Göttingen ohne die Stadt Göttingen",
                "DÜW - Landkreis Bad Dürkheim",
                "DW - Landkreis Sächsische Schweiz-Osterzgebirge",
                "DZ - Landkreis Nordsachsen",
                "E - Stadt Essen",
                "EA - Stadt Eisenach",
                "EB - Landkreis Nordsachsen",
                "EBE - Landkreis Ebersberg",
                "EBN - Landkreis Haßberge",
                "EBS - Landkreis Bayreuth/Forchheim/Kulmbach",
                "ECK - Kreis Rendsburg-Eckernförde",
                "ED - Landkreis Erding",
                "EE - Landkreis Elbe-Elster",
                "EF - Stadt Erfurt; Thüringer Polizei",
                "EG - Landkreis Rottal-Inn",
                "EI - Landkreis Eichstätt",
                "EIC - Landkreis Eichsfeld",
                "EIL - Landkreis Mansfeld-Südharz",
                "EIN - Landkreis Northeim",
                "EIS - Saale-Holzland-Kreis",
                "EL - Landkreis Emsland",
                "EM - Landkreis Emmendingen",
                "EMD - Stadt Emden",
                "EMS - Rhein-Lahn-Kreis",
                "EN - Ennepe-Ruhr-Kreis",
                "ER - Stadt Erlangen",
                "ERB - Odenwaldkreis",
                "ERH - Landkreis Erlangen-Höchstadt",
                "ERK - Kreis Heinsberg",
                "ERZ - Erzgebirgskreis",
                "ES - Landkreis Esslingen",
                "ESB - Landkreis Amberg-Sulzbach/Bayreuth/Neustadt an der Waldnaab/Nürnberger Land",
                "ESW - Werra-Meißner-Kreis",
                "EU - Kreis Euskirchen",
                "EW - Landkreis Barnim",
                "F - Stadt Frankfurt am Main",
                "FB - Wetteraukreis",
                "FD - Landkreis Fulda",
                "FDB - Landkreis Aichach-Friedberg",
                "FDS - Landkreis Freudenstadt",
                "FEU - Landkreis Ansbach",
                "FF - Stadt Frankfurt (Oder)",
                "FFB - Landkreis Fürstenfeldbruck",
                "FG - Landkreis Mittelsachsen",
                "FI - Landkreis Elbe-Elster",
                "FKB - Landkreis Waldeck-Frankenberg",
                "FL - Stadt Flensburg",
                "FLÖ - Landkreis Mittelsachsen",
                "FN - Bodenseekreis",
                "FO - Landkreis Forchheim",
                "FOR - Landkreis Spree-Neiße",
                "FR - Stadt Freiburg im Breisgau; Landkreis Breisgau-Hochschwarzwald",
                "FRG - Landkreis Freyung-Grafenau",
                "FRI - Landkreis Friesland",
                "FRW - Landkreis Märkisch-Oderland",
                "FS - Landkreis Freising",
                "FT - Stadt Frankenthal (Pfalz)",
                "FTL - Landkreis Sächsische Schweiz-Osterzgebirge",
                "FÜ - Stadt/Landkreis Fürth",
                "FÜS - Landkreis Ostallgäu",
                "FZ - Schwalm-Eder-Kreis",
                "G - Stadt Gera",
                "GA - Altmarkkreis Salzwedel",
                "GAN - Landkreis Northeim",
                "GAP - Landkreis Garmisch-Partenkirchen",
                "GC - Landkreis Zwickau",
                "GD - Ostalbkreis",
                "GDB - Landkreis Nordwestmecklenburg",
                "GE - Stadt Gelsenkirchen",
                "GEL - Kreis Kleve",
                "GEO - Landkreis Haßberge/Schweinfurt",
                "GER - Landkreis Germersheim",
                "GF - Landkreis Gifhorn",
                "GG - Kreis Groß-Gerau",
                "GHA - Landkreis Leipzig",
                "GHC - Landkreis Wittenberg",
                "GI - Landkreis Gießen",
                "GK - Kreis Heinsberg",
                "GL - Rheinisch-Bergischer Kreis",
                "GLA - Kreis Recklinghausen",
                "GM - Oberbergischer Kreis",
                "GMN - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
                "GN - Main-Kinzig-Kreis ohne die Stadt Hanau",
                "GNT - Landkreis Jerichower Land",
                "GÖ - Stadt/Landkreis/Polizeidirektion Göttingen",
                "GOA - Rhein-Hunsrück-Kreis",
                "GOH - Rhein-Lahn-Kreis",
                "GP - Landkreis Göppingen",
                "GR - Landkreis Görlitz",
                "GRA - Landkreis Freyung-Grafenau",
                "GRH - Landkreis Meißen",
                "GRI - Landkreis Rottal-Inn",
                "GRM - Landkreis Leipzig",
                "GRZ - Landkreis Greiz",
                "GS - Landkreis Goslar",
                "GT - Kreis Gütersloh",
                "GTH - Landkreis Gotha",
                "GÜ - Landkreis Rostock",
                "GUB - Landkreis Spree-Neiße",
                "GUN - Landkreis Weißenburg-Gunzenhausen",
                "GV - Rhein-Kreis Neuss",
                "GVM - Landkreis Nordwestmecklenburg",
                "GW - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
                "GZ - Landkreis Günzburg",
                "H - Region/Stadt Hannover; Polizeidirektion Niedersachsen (Zentrale)/Hannover",
                "HA - Stadt Hagen",
                "HAB - Landkreis Bad Kissingen",
                "HAL - Stadt Halle (Saale)",
                "HAM - Stadt Hamm",
                "HAS - Landkreis Haßberge",
                "HB - Stadt Bremen/Bremerhaven; Senat, Bürgerschaft",
                "HBN - Landkreis Hildburghausen",
                "HBS - Landkreis Harz",
                "HC - Landkreis Mittelsachsen",
                "HCH - Zollernalbkreis",
                "HD - Stadt Heidelberg; Rhein-Neckar-Kreis",
                "HDH - Landkreis Heidenheim",
                "HDL - Landkreis Börde",
                "HE - Landkreis Helmstedt",
                "HEB - Landkreis Nürnberger Land",
                "HEF - Landkreis Hersfeld-Rotenburg",
                "HEI - Kreis Dithmarschen",
                "HEL - Hessen, Landesregierung, Landtag",
                "HER - Stadt Herne",
                "HET - Landkreis Mansfeld-Südharz",
                "HF - Kreis Herford",
                "HG - Hochtaunuskreis",
                "HGN - Landkreis Ludwigslust-Parchim",
                "HGW - Stadt Greifswald",
                "HH - Freie und Hansestadt Hamburg, Senat, Bürgerschaft",
                "HHM - Burgenlandkreis",
                "HI - Landkreis Hildesheim",
                "HIG - Landkreis Eichsfeld",
                "HIP - Landkreis Roth",
                "HK - Landkreis Heidekreis",
                "HL - Stadt Lübeck",
                "HM - Landkreis Hameln-Pyrmont",
                "HMÜ - Landkreis Göttingen ohne die Stadt Göttingen",
                "HN - Stadt/Landkreis Heilbronn",
                "HO - Stadt/Landkreis Hof",
                "HOG - Landkreis Kassel",
                "HOH - Landkreis Haßberge",
                "HOL - Landkreis Holzminden",
                "HOM - Saarpfalz-Kreis ohne die Stadt St. Ingbert",
                "HOR - Landkreis Freudenstadt",
                "HÖS - Landkreis Erlangen-Höchstadt",
                "HOT - Landkreis Zwickau",
                "HP - Kreis Bergstraße",
                "HR - Schwalm-Eder-Kreis",
                "HRO - Stadt Rostock",
                "HS - Kreis Heinsberg",
                "HSK - Hochsauerlandkreis",
                "HST - Stadt Stralsund",
                "HU - Stadt Hanau; Main-Kinzig-Kreis",
                "HV - Landkreis Stendal",
                "HVL - Landkreis Havelland",
                "HWI - Stadt Wismar",
                "HX - Kreis Höxter",
                "HY - Landkreis Bautzen",
                "HZ - Landkreis Harz",
                "IGB - Stadt St. Ingbert",
                "IK - Ilm-Kreis",
                "IL - Ilm-Kreis",
                "ILL - Landkreis Neu-Ulm",
                "IN - Stadt Ingolstadt; Polizeipräsidium Oberbayern Nord",
                "IZ - Kreis Steinburg",
                "J - Stadt Jena",
                "JE - Landkreis Wittenberg",
                "JL - Landkreis Jerichower Land",
                "JÜL - Kreis Düren",
                "K - Stadt Köln",
                "KA - Stadt/Landkreis Karlsruhe",
                "KB - Landkreis Waldeck-Frankenberg",
                "KC - Landkreis Kronach",
                "KE - Stadt Kempten (Allgäu); Polizeipräsidium Schwaben Süd/West",
                "KEH - Landkreis Kelheim",
                "KEL - Ortenaukreis",
                "KEM - Landkreis Bayreuth/Tirschenreuth",
                "KF - Stadt Kaufbeuren",
                "KG - Landkreis Bad Kissingen",
                "KH - Landkreis Bad Kreuznach",
                "KI - Stadt Kiel",
                "KIB - Donnersbergkreis",
                "KK - Kreis Viersen",
                "KL - Stadt/Landkreis Kaiserslautern",
                "KLE - Kreis Kleve",
                "KLZ - Altmarkkreis Salzwedel",
                "KM - Landkreis Bautzen",
                "KN - Landkreis Konstanz ohne die Gemeinde Büsingen am Hochrhein",
                "KO - Stadt Koblenz",
                "KÖN - Landkreis Rhön-Grabfeld",
                "KÖT - Landkreis Anhalt-Bitterfeld",
                "KÖZ - Landkreis Cham",
                "KR - Stadt Krefeld",
                "KRU - Landkreis Günzburg",
                "KS - Stadt/Landkreis Kassel",
                "KT - Landkreis Kitzingen",
                "KU - Landkreis Kulmbach",
                "KÜN - Hohenlohekreis",
                "KUS - Landkreis Kusel",
                "KW - Landkreis Dahme-Spreewald",
                "KY - Landkreis Ostprignitz-Ruppin",
                "KYF - Kyffhäuserkreis",
                "L - Stadt/Landkreis Leipzig",
                "LA - Stadt/Landkreis Landshut",
                "LAN - Landkreis Dingolfing-Landau",
                "LAU - Landkreis Nürnberger Land",
                "LB - Landkreis Ludwigsburg",
                "LBS - Saale-Orla-Kreis",
                "LBZ - Landkreis Ludwigslust-Parchim",
                "LC - Landkreis Dahme-Spreewald",
                "LD - Stadt Landau in der Pfalz",
                "LDK - Lahn-Dill-Kreis ohne die Stadt Wetzlar",
                "LDS - Landkreis Dahme-Spreewald",
                "LEO - Landkreis Böblingen",
                "LER - Landkreis Leer",
                "LEV - Stadt Leverkusen",
                "LF - Landkreis Altötting/Berchtesgadener Land/Traunstein",
                "LG - Landkreis/Polizeidirektion Lüneburg",
                "LH - Kreis Coesfeld/Unna",
                "LI - Landkreis Lindau (Bodensee)",
                "LIB - Landkreis Elbe-Elster",
                "LIF - Landkreis Lichtenfels",
                "LIP - Kreis Lippe",
                "LL - Landkreis Landsberg am Lech",
                "LM - Landkreis Limburg-Weilburg",
                "LN - Landkreis Dahme-Spreewald",
                "LÖ - Landkreis Lörrach",
                "LÖB - Landkreis Görlitz",
                "LOS - Landkreis Oder-Spree",
                "LP - Kreis Soest",
                "LR - Ortenaukreis",
                "LRO - Landkreis Rostock",
                "LSA - Sachsen-Anhalt, Landesregierung, Landtag, Polizei",
                "LSN - Sachsen, Landesregierung, Landtag",
                "LSZ - Unstrut-Hainich-Kreis",
                "LU - Stadt Ludwigshafen am Rhein",
                "LÜN - Kreis Unna",
                "LUP - Landkreis Ludwigslust-Parchim",
                "LWL - Landkreis Ludwigslust-Parchim",
                "M - Stadt/Landkreis/Polizeipräsidum München",
                "MA - Stadt Mannheim",
                "MAB - Erzgebirgskreis",
                "MAI - Landkreis Kelheim/Landshut",
                "MAK - Landkreis Wunsiedel im Fichtelgebirge",
                "MAL - Landkreis Landshut",
                "MB - Landkreis Miesbach",
                "MC - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "MD - Stadt Magdeburg",
                "ME - Kreis Mettmann",
                "MED - Kreis Dithmarschen",
                "MEG - Schwalm-Eder-Kreis",
                "MEI - Landkreis Meißen",
                "MEK - Erzgebirgskreis",
                "MER - Saalekreis",
                "MET - Landkreis Rhön-Grabfeld",
                "MG - Stadt Mönchengladbach",
                "MGH - Main-Tauber-Kreis",
                "MGN - Landkreis Schmalkalden-Meiningen",
                "MH - Stadt Mülheim an der Ruhr",
                "MHL - Unstrut-Hainich-Kreis",
                "MI - Kreis Minden-Lübbecke",
                "MIL - Landkreis Miltenberg",
                "MK - Märkischer Kreis",
                "MKK - Main-Kinzig-Kreis ohne die Stadt Hanau",
                "ML - Landkreis Mansfeld-Südharz",
                "MM - Stadt Memmingen",
                "MN - Landkreis Unterallgäu",
                "MO - Kreis Wesel",
                "MOD - Landkreis Ostallgäu",
                "MOL - Landkreis Märkisch-Oderland",
                "MON - Städteregion Aachen; Kreis Düren",
                "MOS - Neckar-Odenwald-Kreis",
                "MQ - Saalekreis",
                "MR - Landkreis Marburg-Biedenkopf",
                "MS - Stadt Münster",
                "MSE - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "MSH - Landkreis Mansfeld-Südharz",
                "MSP - Landkreis Main-Spessart",
                "MST - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "MTK - Main-Taunus-Kreis",
                "MTL - Landkreis Leipzig",
                "MÜ - Landkreis Mühldorf am Inn",
                "MÜB - Landkreis Bayreuth/Hof",
                "MÜR - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "MVL - Mecklenburg-Vorpommern, Landesregierung, Landtag, Polizei",
                "MW - Landkreis Mittelsachsen",
                "MY - Landkreis Mayen-Koblenz",
                "MYK - Landkreis Mayen-Koblenz",
                "MZ - Stadt Mainz; Landkreis Mainz-Bingen",
                "MZG - Landkreis Merzig-Wadern",
                "N - Stadt Nürnberg; Landkreis Nürnberger Land; Polizeipräsidum Mittelfranken",
                "NAB - Landkreis Amberg-Sulzbach/Schwandorf",
                "NAI - Landkreis Hof",
                "NAU - Landkreis Havelland",
                "NB - Stadt Neubrandenburg",
                "ND - Landkreis Neuburg-Schrobenhausen",
                "NDH - Landkreis Nordhausen",
                "NE - Rhein-Kreis Neuss",
                "NEA - Landkreis Neustadt an der Aisch-Bad Windsheim",
                "NEB - Burgenlandkreis",
                "NEC - Stadt/Landkreis Coburg",
                "NEN - Landkreis Schwandorf",
                "NES - Landkreis Rhön-Grabfeld",
                "NEW - Landkreis Neustadt an der Waldnaab",
                "NF - Kreis Nordfriesland",
                "NH - Landkreis Sonneberg",
                "NI - Landkreis Nienburg/Weser",
                "NK - Landkreis Neunkirchen",
                "NL - Niedersachsen, Landesregierung, Landtag",
                "NM - Landkreis Neumarkt in der Oberpfalz",
                "NMB - Burgenlandkreis",
                "NMS - Stadt Neumünster",
                "NÖ - Landkreis Donau-Ries",
                "NOH - Landkreis Grafschaft Bentheim",
                "NOL - Landkreis Görlitz",
                "NOM - Landkreis Northeim",
                "NOR - Landkreis Aurich",
                "NP - Landkreis Ostprignitz-Ruppin",
                "NR - Landkreis Neuwied",
                "NRW - Nordrhein-Westfalen, Landesregierung, Landtag, Polizei",
                "NT - Landkreis Esslingen",
                "NU - Landkreis Neu-Ulm",
                "NVP - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
                "NW - Stadt Neustadt an der Weinstraße",
                "NWM - Landkreis Nordwestmecklenburg ohne die Stadt Wismar",
                "NY - Landkreis Görlitz",
                "NZ - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "OA - Landkreis Oberallgäu",
                "OAL - Landkreis Ostallgäu",
                "OB - Stadt Oberhausen",
                "OBG - Landkreis Stendal",
                "OC - Landkreis Börde",
                "OCH - Landkreis Würzburg",
                "OD - Kreis Stormarn",
                "OE - Kreis Olpe",
                "OF - Landkreis Offenbach; Stadt Offenbach am Main",
                "OG - Ortenaukreis",
                "OH - Kreis Ostholstein",
                "OHA - Landkreis Göttingen",
                "ÖHR - Hohenlohekreis",
                "OHV - Landkreis Oberhavel",
                "OHZ - Landkreis Osterholz",
                "OK - Landkreis Börde",
                "OL - Stadt/Landkreis/Polizeidirektion Oldenburg",
                "OP - Stadt Leverkusen",
                "OPR - Landkreis Ostprignitz-Ruppin",
                "OS - Stadt/Landkreis/Polizeidirektion Osnabrück",
                "OSL - Landkreis Oberspreewald-Lausitz",
                "OVI - Landkreis Schwandorf",
                "OVL - Vogtlandkreis",
                "OZ - Landkreis Nordsachsen",
                "P - Stadt Potsdam",
                "PA - Stadt/Landkreis Passau",
                "PAF - Landkreis Pfaffenhofen an der Ilm",
                "PAN - Landkreis Rottal-Inn",
                "PAR - Landkreis Kelheim/Neumarkt in der Oberpfalz",
                "PB - Kreis Paderborn",
                "PCH - Landkreis Ludwigslust-Parchim",
                "PE - Landkreis Peine",
                "PEG - Landkreis Bayreuth/Forchheim/Nürnberger Land",
                "PF - Stadt Pforzheim; Enzkreis",
                "PI - Kreis Pinneberg",
                "PIR - Landkreis Sächsische Schweiz-Osterzgebirge",
                "PL - Vogtlandkreis",
                "PLÖ - Kreis Plön",
                "PM - Landkreis Potsdam-Mittelmark",
                "PN - Saale-Orla-Kreis",
                "PR - Landkreis Prignitz",
                "PRÜ - Eifelkreis Bitburg-Prüm",
                "PS - Stadt Pirmasens; Landkreis Südwestpfalz",
                "PW - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
                "PZ - Landkreis Uckermark",
                "QFT - Saalekreis",
                "QLB - Landkreis Harz",
                "R - Stadt/Landkreis Regensburg; Polizeipräsidum Oberpfalz",
                "RA - Landkreis Rastatt",
                "RC - Vogtlandkreis",
                "RD - Kreis Rendsburg-Eckernförde",
                "RDG - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
                "RE - Kreis Recklinghausen",
                "REG - Landkreis Regen",
                "REH - Landkreis Hof/Wunsiedel im Fichtelgebirge",
                "REI - Landkreis Berchtesgadener Land",
                "RG - Landkreis Meißen",
                "RH - Landkreis Roth",
                "RI - Landkreis Schaumburg",
                "RID - Landkreis Kelheim",
                "RIE - Landkreis Meißen",
                "RL - Landkreis Mittelsachsen",
                "RM - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "RN - Landkreis Havelland",
                "RO - Stadt/Landkreis Rosenheim; Polizeipräsidum Oberbayern Süd",
                "ROD - Landkreis Cham/Schwandorf",
                "ROF - Landkreis Hersfeld-Rotenburg",
                "ROK - Donnersbergkreis",
                "ROL - Landkreis Kelheim/Landshut",
                "ROS - Landkreis Rostock",
                "ROT - Landkreis Ansbach",
                "ROW - Landkreis Rotenburg (Wümme)",
                "RP - Rhein-Pfalz-Kreis",
                "RPL - Rheinland-Pfalz, Landesregierung, Landtag, Polizei",
                "RS - Stadt Remscheid",
                "RSL - Stadt Dessau-Roßlau",
                "RT - Landkreis Reutlingen",
                "RU - Landkreis Saalfeld-Rudolstadt",
                "RÜD - Rheingau-Taunus-Kreis",
                "RÜG - Landkreis Vorpommern-Rügen",
                "RV - Landkreis Ravensburg",
                "RW - Landkreis Rottweil",
                "RZ - Kreis Herzogtum Lauenburg",
                "S - Stadt Stuttgart",
                "SAB - Landkreis Trier-Saarburg",
                "SAD - Landkreis Schwandorf",
                "SAL - Saarland, Landesregierung, Landtag, Polizei",
                "SAN - Landkreis Hof/Kronach/Kulmbach",
                "SAW - Altmarkkreis Salzwedel",
                "SB - Regionalverband Saarbrücken ohne die Stadt Völklingen",
                "SBG - Landkreis Vorpommern-Greifswald",
                "SBK - Salzlandkreis",
                "SC - Stadt Schwabach",
                "SCZ - Saale-Orla-Kreis",
                "SDH - Kyffhäuserkreis",
                "SDL - Landkreis Stendal",
                "SDT - Landkreis Uckermark",
                "SE - Kreis Segeberg",
                "SEB - Landkreis Sächsische Schweiz-Osterzgebirge",
                "SEE - Landkreis Märkisch-Oderland",
                "SEF - Landkreis Neustadt an der Aisch-Bad Windsheim",
                "SEL - Landkreis Wunsiedel im Fichtelgebirge",
                "SFB - Landkreis Oberspreewald-Lausitz",
                "SFT - Salzlandkreis",
                "SG - Stadt Solingen",
                "SGH - Landkreis Mansfeld-Südharz",
                "SH - Schleswig-Holstein, Landesregierung, Landtag, Polizei",
                "SHA - Landkreis Schwäbisch Hall",
                "SHG - Landkreis Schaumburg",
                "SHK - Saale-Holzland-Kreis",
                "SHL - Stadt Suhl",
                "SI - Kreis Siegen-Wittgenstein",
                "SIG - Landkreis Sigmaringen",
                "SIM - Rhein-Hunsrück-Kreis",
                "SK - Saalekreis",
                "SL - Kreis Schleswig-Flensburg",
                "SLE - Kreis Düren/Euskirchen",
                "SLF - Landkreis Saalfeld-Rudolstadt",
                "SLK - Salzlandkreis",
                "SLN - Landkreis Altenburger Land",
                "SLS - Landkreis Saarlouis",
                "SLÜ - Main-Kinzig-Kreis ohne die Stadt Hanau",
                "SLZ - Wartburgkreis",
                "SM - Landkreis Schmalkalden-Meiningen",
                "SMÜ - Landkreis Augsburg",
                "SN - Stadt Schwerin",
                "SO - Kreis Soest",
                "SOB - Landkreis Neuburg-Schrobenhausen",
                "SOG - Landkreis Weilheim-Schongau",
                "SOK - Saale-Orla-Kreis",
                "SÖM - Landkreis Sömmerda",
                "SON - Landkreis Sonneberg",
                "SP - Stadt Speyer",
                "SPB - Landkreis Spree-Neiße",
                "SPN - Landkreis Spree-Neiße",
                "SR - Landkreis Straubing-Bogen; Stadt Straubing; Polizeipräsidum Niederbayern",
                "SRB - Landkreis Märkisch-Oderland",
                "SRO - Saale-Holzland-Kreis",
                "ST - Kreis Steinfurt",
                "STA - Landkreis Starnberg",
                "STB - Landkreis Ludwigslust-Parchim",
                "STD - Landkreis Stade",
                "STE - Landkreis Lichtenfels",
                "STL - Erzgebirgskreis",
                "SU - Rhein-Sieg-Kreis",
                "SUL - Landkreis Amberg-Sulzbach",
                "SÜW - Landkreis Südliche Weinstraße",
                "SW - Stadt/Landkreis Schweinfurt",
                "SWA - Rheingau-Taunus-Kreis",
                "SZ - Stadt Salzgitter",
                "SZB - Erzgebirgskreis",
                "TBB - Main-Tauber-Kreis",
                "TDO - Landkreis Nordsachsen",
                "TE - Kreis Steinfurt",
                "TET - Landkreis Rostock",
                "TF - Landkreis Teltow-Fläming",
                "TG - Landkreis Nordsachsen",
                "THL - Thüringen, Landesregierung, Landtag",
                "THW - Bundesanstalt Technisches Hilfswerk",
                "TIR - Landkreis Tirschenreuth",
                "TO - Landkreis Nordsachsen",
                "TÖL - Landkreis Bad Tölz-Wolfratshausen",
                "TP - Landkreis Uckermark",
                "TR - Landkreis Trier-Saarburg; Stadt Trier",
                "TS - Landkreis Traunstein",
                "TÜ - Landkreis Tübingen",
                "TUT - Landkreis Tuttlingen",
                "UE - Landkreis Uelzen",
                "UEM - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
                "UFF - Landkreis Neustadt an der Aisch-Bad Windsheim",
                "UH - Unstrut-Hainich-Kreis",
                "UL - Stadt Ulm; Alb-Donau-Kreis",
                "UM - Landkreis Uckermark",
                "UN - Kreis Unna",
                "USI - Hochtaunuskreis",
                "V - Vogtlandkreis",
                "VAI - Landkreis Ludwigsburg",
                "VB - Vogelsbergkreis",
                "VEC - Landkreis Vechta",
                "VER - Landkreis Verden",
                "VG - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
                "VIB - Landkreis Landshut/Rottal-Inn",
                "VIE - Kreis Viersen",
                "VK - Stadt Völklingen",
                "VOH - Landkreis Neustadt an der Waldnaab",
                "VR - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
                "VS - Schwarzwald-Baar-Kreis",
                "W - Stadt Wuppertal",
                "WA - Landkreis Waldeck-Frankenberg",
                "WAF - Kreis Warendorf",
                "WAK - Wartburgkreis",
                "WAN - Stadt Herne",
                "WAT - Stadt Bochum",
                "WB - Landkreis Wittenberg",
                "WBS - Landkreis Eichsfeld",
                "WDA - Landkreis Zwickau",
                "WE - Stadt Weimar",
                "WEL - Landkreis Limburg-Weilburg",
                "WEN - Stadt Weiden in der Oberpfalz",
                "WER - Landkreis Augsburg/Dillingen an der Donau",
                "WES - Kreis Wesel",
                "WF - Landkreis Wolfenbüttel",
                "WHV - Stadt Wilhelmshaven",
                "WI - Stadt Wiesbaden; Hessische Polizei",
                "WIL - Landkreis Bernkastel-Wittlich",
                "WIS - Landkreis Nordwestmecklenburg",
                "WIT - Ennepe-Ruhr-Kreis",
                "WIZ - Werra-Meißner-Kreis",
                "WK - Landkreis Ostprignitz-Ruppin",
                "WL - Landkreis Harburg",
                "WLG - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
                "WM - Landkreis Weilheim-Schongau",
                "WMS - Landkreis Börde",
                "WN - Rems-Murr-Kreis",
                "WND - Landkreis St. Wendel",
                "WO - Stadt Worms",
                "WOB - Stadt Wolfsburg",
                "WOH - Landkreis Kassel",
                "WOL - Ortenaukreis",
                "WOR - Landkreis Bad Tölz-Wolfratshausen/München/Starnberg",
                "WOS - Landkreis Freyung-Grafenau",
                "WR - Landkreis Harz",
                "WRN - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
                "WS - Landkreis Rosenheim",
                "WSF - Burgenlandkreis",
                "WST - Landkreis Ammerland",
                "WSW - Landkreis Görlitz",
                "WT - Landkreis Waldshut",
                "WTM - Landkreis Wittmund",
                "WÜ - Stadt/Landkreis Würzburg; Polizeipräsidum Unterfranken",
                "WUG - Landkreis Weißenburg-Gunzenhausen",
                "WÜM - Landkreis Cham",
                "WUN - Landkreis Wunsiedel im Fichtelgebirge",
                "WUR - Landkreis Leipzig",
                "WW - Westerwaldkreis",
                "WZ - Stadt Wetzlar",
                "WZL - Landkreis Börde",
                "X - Internationale Hauptquartiere (NATO)",
                "Y - Bundeswehr",
                "Z - Landkreis Zwickau",
                "ZE - Landkreis Anhalt-Bitterfeld",
                "ZEL - Landkreis Cochem-Zell",
                "ZI - Landkreis Görlitz",
                "ZIG - Schwalm-Eder-Kreis",
                "ZP - Erzgebirgskreis",
                "ZR - Landkreis Greiz",
                "ZW - Stadt Zweibrücken; Landkreis Südwestpfalz",
                "ZZ - Burgenlandkreis"
            ],
            [
                "AG - Aargau",
                "AI - Appenzell Innerrhoden",
                "AR - Appenzell Ausserrhoden",
                "BE - Bern",
                "BL - Basel-Landschaft",
                "BS - Basel-Stadt",
                "FR - Fribourg",
                "GE - Geneva",
                "GL - Glarus",
                "GR - Graubünden",
                "JU - Jura",
                "LU - Lucerne",
                "NE - Neuchâtel",
                "NW - Nidwalden",
                "OW - Obwalden",
                "SG - St. Gallen",
                "SH - Schaffhausen",
                "SO - Solothurn",
                "SZ - Schwyz",
                "TG - Thurgau",
                "TI - Ticino",
                "UR - Uri",
                "VD - Vaud",
                "VS - Valais",
                "ZG - Zug",
                "ZH - Zürich"
            ],
            [
                "01 - Ain/Bourg-en-Bresse/Auvergne-Rhône-Alpes",
                "02 - Aisne/Laon/Hauts-de-France",
                "03 - Allier/Moulins/Auvergne-Rhône-Alpes",
                "04 - Alpes-de-Haute-Provence/Digne-les-Bains/Provence-Alpes-Côte d'Azur",
                "05 - Hautes-Alpes/Gap/Provence-Alpes-Côte d'Azur",
                "06 - Alpes-Maritimes/Nice/Provence-Alpes-Côte d'Azur",
                "07 - Ardèche/Privas/Auvergne-Rhône-Alpes",
                "08 - Ardennes/Charleville-Mézières/Grand Est",
                "09 - Ariège/Foix/Occitanie",
                "10 - Aube/Troyes/Grand Est",
                "11 - Aude/Carcassonne/Occitanie",
                "12 - Aveyron/Rodez/Occitanie",
                "13 - Bouches-du-Rhône/Marseille/Provence-Alpes-Côte d'Azur",
                "14 - Calvados/Caen/Normandy",
                "15 - Cantal/Aurillac/Auvergne-Rhône-Alpes",
                "16 - Charente/Angoulême/Nouvelle-Aquitaine",
                "17 - Charente-Maritime/La/Rochelle/Nouvelle-Aquitaine",
                "18 - Cher/Bourges/Centre-Val de Loire",
                "19 - Corrèze/Tulle/Nouvelle-Aquitaine",
                "2A - Corse-du-Sud/Ajaccio/Corsica",
                "2B - Haute-Corse/Bastia/Corsica",
                "21 - Côte-d'Or/Dijon/Bourgogne-Franche-Comté",
                "22 - Côtes-d'Armor/Saint-Brieuc/Brittany",
                "23 - Creuse/Guéret/Nouvelle-Aquitaine",
                "24 - Dordogne/Périgueux/Nouvelle-Aquitaine",
                "25 - Doubs/Besançon/Bourgogne-Franche-Comté",
                "26 - Drôme/Valence/Auvergne-Rhône-Alpes",
                "27 - Eure/Évreux/Normandy",
                "28 - Eure-et-Loir/Chartres/Centre-Val de Loire",
                "29 - Finistère/Quimper/Brittany",
                "30 - Gard/Nîmes/Occitanie",
                "31 - Haute-Garonne/Toulouse/Occitanie",
                "32 - Gers/Auch/Occitanie",
                "33 - Gironde/Bordeaux/Nouvelle-Aquitaine",
                "34 - Hérault/Montpellier/Occitanie",
                "35 - Ille-et-Vilaine/Rennes/Brittany",
                "36 - Indre/Châteauroux/Centre-Val de Loire",
                "37 - Indre-et-Loire/Tours/Centre-Val de Loire",
                "38 - Isère/Grenoble/Auvergne-Rhône-Alpes",
                "39 - Jura/Lons-le-Saunier/Bourgogne-Franche-Comté",
                "40 - Landes/Mont-de-Marsan/Nouvelle-Aquitaine",
                "41 - Loir-et-Cher/Blois/Centre-Val de Loire",
                "42 - Loire/Saint-Étienne/Auvergne-Rhône-Alpes",
                "43 - Haute-Loire/Le/Puy-en-Velay/Auvergne-Rhône-Alpes",
                "44 - Loire-Atlantique 6/Nantes/Pays de la Loire",
                "45 - Loiret/Orléans/Centre-Val de Loire",
                "46 - Lot/Cahors/Occitanie",
                "47 - Lot-et-Garonne/Agen/Nouvelle-Aquitaine",
                "48 - Lozère/Mende/Occitanie",
                "49 - Maine-et-Loire/Angers/Pays de la Loire",
                "50 - Manche/Saint-Lô/Normandy",
                "51 - Marne/Châlons-en-Champagne/Grand Est",
                "52 - Haute-Marne/Chaumont/Grand Est",
                "53 - Mayenne/Laval/Pays de la Loire",
                "54 - Meurthe-et-Moselle/Nancy/Grand Est",
                "55 - Meuse/Bar-le-Duc/Grand Est",
                "56 - Morbihan/Vannes/Brittany",
                "57 - Moselle/Metz/Grand Est",
                "58 - Nièvre/Nevers/Bourgogne-Franche-Comté",
                "59 - Nord/Lille/Hauts-de-France",
                "60 - Oise/Beauvais/Hauts-de-France",
                "61 - Orne/Alençon/Normandy",
                "62 - Pas-de-Calais/Arras/Hauts-de-France",
                "63 - Puy-de-Dôme/Clermont-Ferrand/Auvergne-Rhône-Alpes",
                "64 - Pyrénées-Atlantiques 8/Pau/Nouvelle-Aquitaine",
                "65 - Hautes-Pyrénées/Tarbes/Occitanie",
                "66 - Pyrénées-Orientales/Perpignan/Occitanie",
                "67 - Bas-Rhin/Strasbourg/Grand Est",
                "68 - Haut-Rhin/Colmar/Grand Est",
                "69M - Metropolitan Lyon/Lyon/Auvergne-Rhône-Alpes",
                "69 - Rhône/Lyon (provisional)/Auvergne-Rhône-Alpes",
                "70 - Haute-Saône/Vesoul/Bourgogne-Franche-Comté",
                "71 - Saône-et-Loire/Mâcon/Bourgogne-Franche-Comté",
                "72 - Sarthe/Le Mans/Pays de la Loire",
                "73 - Savoie/Chambéry/Auvergne-Rhône-Alpes",
                "74 - Haute-Savoie/Annecy/Auvergne-Rhône-Alpes",
                "75 - Paris/Paris/Île-de-France",
                "76 - Seine-Maritime/Rouen/Normandy",
                "77 - Seine-et-Marne/Melun/Île-de-France",
                "78 - Yvelines/Versailles/Île-de-France",
                "79 - Deux-Sèvres/Niort/Nouvelle-Aquitaine",
                "80 - Somme/Amiens/Hauts-de-France",
                "81 - Tarn/Albi/Occitanie",
                "82 - Tarn-et-Garonne/Montauban/Occitanie",
                "83 - Var/Toulon/Provence-Alpes-Côte d'Azur",
                "84 - Vaucluse/Avignon/Provence-Alpes-Côte d'Azur",
                "85 - Vendée/La/Roche-sur-Yon/Pays de la Loire",
                "86 - Vienne/Poitiers/Nouvelle-Aquitaine",
                "87 - Haute-Vienne/Limoges/Nouvelle-Aquitaine",
                "88 - Vosges/Épinal/Grand Est",
                "89 - Yonne/Auxerre/Bourgogne-Franche-Comté",
                "90 - Territoire/de/Belfort/Belfort/Bourgogne-Franche-Comté",
                "91 - Essonne/Évry/Île-de-France",
                "92 - Hauts-de-Seine/Nanterre/Île-de-France",
                "93 - Seine-Saint-Denis/Bobigny/Île-de-France",
                "94 - Val-de-Marne/Créteil/Île-de-France",
                "95 - Val-d'Oise/Pontoise/Île-de-France",
                "971 - Guadeloupe/Basse-Terre/Guadeloupe",
                "972 - Martinique/Fort-de-France/Martinique",
                "973 - Guyane/Cayenne/French Guiana",
                "974 - La Réunion/Saint-Denis/Réunion",
                "976 - Mayotte/Mamoudzou/Mayotte",

            ]
        ]
