//  Copyright © 2017-9 Arc676/Alessandro Vinciguerra. All rights reserved.
//  Text in just this file available under Wikipedia's Creative Commons License
//  (Text of Creative Commons Attribution-ShareAlike 3.0 Unported License).

// Sources
// https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_China
// https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Italy
// https://de.wikipedia.org/wiki/Diplomatenkennzeichen_(Deutschland)
// https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Switzerland
// https://de.wikipedia.org/wiki/Liste_der_Kfz-Kennzeichen_in_Deutschland
// https://en.wikipedia.org/wiki/Departments_of_France

var searchItems = [
			[
				"101 - Afghanistan",
				"102 - Albania",
				"103 - Algeria",
				"104 - Angola",
				"105 - Argentina",
				"106 - Australia",
				"107 - Austria",
				"108 - Azerbaijan",
				"109 - Bahrain",
				"110 - Bangladesh",
				"111 - Belarus",
				"112 - Belgium",
				"113 - Benin",
				"114 - Bolivia",
				"115 - Botswana",
				"116 - Brazil",
				"117 - Brunei",
				"118 - Bulgaria",
				"119 - Burkina Faso",
				"120 - Burundi",
				"121 - Cambodia",
				"122 - Cameroon",
				"123 - Canada",
				"124 - Chad",
				"125 - Chile",
				"126 - Colombia",
				"127 - Congo",
				"128 - Ivory Coast",
				"129 - Croatia",
				"130 - Cuba",
				"131 - Cyprus",
				"132 - Czech Rep.",
				"133 - N. Korea",
				"134 - Denmark",
				"135 - E. Timor",
				"136 - Ecuador",
				"137 - Egypt",
				"138 - Equatorial Guinea",
				"139 - Eritrea",
				"140 - Ethiopia",
				"141 - Fiji",
				"142 - Finland",
				"143 - France",
				"144 - Gabon",
				"145 - Germany",
				"146 - Ghana",
				"147 - Greece",
				"148 - Guinea",
				"149 - Guyana",
				"150 - Hungary",
				"151 - Iceland",
				"152 - India",
				"153 - Indonesia",
				"154 - Iran",
				"155 - Iraq",
				"156 - Ireland",
				"157 - Israel",
				"158 - Italy",
				"160 - Jordan",
				"161 - Kazakhstan",
				"162 - Kenya",
				"163 - Kiribati",
				"164 - Kuwait",
				"165 - Kyrgyzstan",
				"166 - Laos",
				"167 - Lebanon",
				"168 - Libya",
				"169 - Luxembourg",
				"170 - Madagascar",
				"171 - Malaysia",
				"172 - Mali",
				"173 - Malta",
				"174 - Marshall Islands",
				"175 - Mauritania",
				"176 - Mexico",
				"177 - Micronesia",
				"178 - Mongolia",
				"179 - Morocco",
				"180 - Mozambique",
				"181 - Myanmar",
				"182 - Nepal",
				"183 - Netherlands",
				"184 - New Zealand",
				"185 - Nigeria",
				"186 - Norway",
				"187 - Oman",
				"188 - Pakistan",
				"189 - Palestine",
				"190 - Papua New Guinea",
				"191 - Peru",
				"192 - Philippines",
				"193 - Poland",
				"194 - Portugal",
				"195 - Qatar",
				"196 - S. Korea",
				"197 - Romania",
				"198 - Russia",
				"199 - Rwanda",
				"200 - Saudi Arabia",
				"201 - Senegal",
				"202 - Seychelles",
				"203 - Sierra Leone",
				"204 - Singapore",
				"205 - Slovakia",
				"206 - Slovenia",
				"207 - Somalia",
				"208 - S. Africa",
				"209 - Spain",
				"210 - Sri Lanka",
				"211 - Sudan",
				"212 - Sweden",
				"213 - Switzerland",
				"214 - Syria",
				"215 - Tanzania",
				"216 - Thailand",
				"217 - Toga",
				"218 - Tunisia",
				"219 - Turkey",
				"220 - Uganda",
				"221 - Ukraine",
				"222 - UAE",
				"223 - UK",
				"224 - US",
				"225 - Uruguay",
				"226 - Vanuatu",
				"227 - Venezuela",
				"228 - Vietnam",
				"229 - Yemen",
				"230 - Serbia",
				"231 - Democratic Rep. of Congo",
				"232 - Zambia",
				"233 - Zimbabwe",
				"234 - Macedonia",
				"235 - Japan",
				"236 - Lesotho",
				"237 - Uzbekistan",
				"238 - Turkmenistan",
				"239 - Georgia",
				"240 - Namibia",
				"241 - Lithuania",
				"242 - Moldova",
				"243 - Mauritius",
				"244 - Panama",
				"245 - Niger",
				"246 - Tajikistan",
				"247 - Antigua and Barbuda",
				"248 - Armenia",
				"249 - Suriname",
				"251 - Estonia",
				"252 - Haiti",
				"253 - Latvia",
				"254 - Bosnia and Herzegovina",
				"255 - Guinea-Bissau",
				"256 - Cape Verde",
				"257 - Djibouti",
				"258 - Central African Rep.",
				"260 - Dominica",
				"261 - Liberia",
				"262 - Jamaica",
				"263 - Grenada",
				"264 - Maldives",
				"265 - Costa Rica",
				"266 - Malawi",
				"267 - Bahamas",
				"268 - Comoros",
				"269 - Montenegro",
				"270 - Tonga",
				"271 - S. Sudan",
				"272 - Barbados",
				"159 - Shanghai Cooperation Organisation",
				"259 - Pacific Islands Forum",
				"300 - EU",
				"301 - Arab League",
				"302 - UN Development Program",
				"303 - UN Food and Agriculture Organization",
				"304 - UN Population Fund",
				"305 - UN World Food Programme",
				"306 - UN Children's Fund",
				"307 - UN World Health Organization",
				"308 - UN Educational, Scientific and Cultural Organization",
				"309 - UN International Labour Organization",
				"310 - World Bank",
				"311 - UN High Commissioner for Refugees",
				"313 - International Monetary Fund",
				"314 - International Finance Corporation",
				"316 - UN Industrial Development Organization",
				"317 - Asia Development Bank",
				"318 - Red Cross",
				"319 - UN Asian and Pacific Centre for Agricultural Engineering and Machinery",
				"321 - UN Environment Programme"
			],
			[
				"皖 - Anhui 安徽",
				"皖A - Hefei 合肥",
				"皖B - Wuhu 芜湖",
				"皖C - Bengbu 蚌埠",
				"皖D - Huainan 淮南",
				"皖E - Ma'anshan 马鞍山",
				"皖F - Huaibei 淮北",
				"皖G - Tongling 铜陵",
				"皖H - Anqing 安庆",
				"皖J - Huangshan 黄山",
				"皖K - Fuyang 阜阳",
				"皖L - Suzhou 宿州",
				"皖M - Chuzhou 滁州",
				"皖N - Lu'an 六安",
				"皖P - Xuancheng 宣称",
				"皖Q - Chaohu 巢湖",
				"皖R - Chizhou 池州",
				"皖S - Bozhou 亳州",
				"闽 - Fujian 福建",
				"闽A - Fuzhou 福州",
				"闽B - Putian 莆田",
				"闽C - Quanzhou 泉州",
				"闽D - Xiamen 厦门",
				"闽E - Zhangzhou 漳州",
				"闽F - Longyan 龙岩",
				"闽G - Sanming 三名",
				"闽H - Nanping 南平",
				"闽J - Ningde 宁德",
				"闽K - Provincial-level agencies, Pingtan island 平潭岛",
				"闽O - Police vehicles 警车",
				"甘 - Gansu 甘肃",
				"甘A - Lanzhou 兰州",
				"甘B - Jiayuguan 嘉峪关",
				"甘C - Jinchang 金昌",
				"甘D - Baiyin 白银",
				"甘E - Tianshui 天水",
				"甘F - Jiuquan 酒泉",
				"甘G - Zhangye 张掖",
				"甘H - Wuwei 武威",
				"甘J - Dingxi 定西",
				"甘K - Longnan 陇南",
				"甘L - Pingliang 平凉",
				"甘M - Qingyang 庆阳",
				"甘N - Linxia Hui Autonomous Prefecture 临夏回族自治州",
				"甘P - Gannan Tibetan Autonomous Prefecture 甘南藏族自治州",
				"粤 - Guangdong 广东",
				"粤A - Guangzhou 广州",
				"粤AQ - Panyu 番禺区",
				"粤B - Shenzhen 深圳",
				"粤C - Zhuhai 珠海",
				"粤D - Shantou 汕头",
				"粤E - Foshan 佛山",
				"粤EV - Gaoming 高明区",
				"粤ET - Sanshui 三水区",
				"粤F - Shaoguan 韶关",
				"粤G - Zhanjiang 湛江",
				"粤H - Zhaoqing 肇庆",
				"粤HL - Sihui 四会",
				"粤J - Jiangmen 江门",
				"粤K - Maoming 茂名",
				"粤L - Huizhou 惠州",
				"粤M - Meizhou 梅州",
				"粤N - Shanwei 汕尾",
				"粤O - Police vehicles 警车",
				"粤P - Heyuan 河源",
				"粤Q - Yangjiang 阳江",
				"粤R - Qingyuan 清远",
				"粤S - Dongguan 东莞",
				"粤T - Zhongshan 中山",
				"粤U - Chaozhou 潮州",
				"粤V - Jieyang 揭阳",
				"粤W - Yunfu 云浮",
				"粤X - Shunde 顺德区",
				"粤Y - Nanhai 南海区",
				"粤Z - Hong Kong 香港 & Macau 澳门",
				"贵 - Guizhou 贵州",
				"贵A - Guiyang 贵阳",
				"贵B - Liupanshui 六盘水",
				"贵C - Zunyi 遵义",
				"贵D - Tongren 铜仁",
				"贵E - Qianxinan Autonomous Prefecture 黔西南布依族苗族自治州",
				"贵F - Bijie 毕节",
				"贵G - Anshun 安顺",
				"贵H - Qiandonnan Autonomous Prefecture 黔东南苗族侗族自治州",
				"贵J - Qiannan Autonomous Prefecture 黔南州布依族苗族自治州",
				"琼 - Hainan 海南",
				"琼A - Haikou 海口",
				"琼B - Sanya 三亚",
				"琼C - Qiongbei 琼海, Wenchang 文昌, Wanning 万宁, Ding'an 定安县, Tunchang 屯昌县, Chengmai 澄迈县, Lingao 临高县",
				"琼D - Wuzhishan 五指山, Dongfang 东方, Baisha 白沙县, Changjiang 昌江县, Ledong 乐东县, Lingshui 陵水县, Baoting 保亭县, Qiongzhong 琼中县",
				"冀 - Hebei 河北",
				"冀A - Shijiazhuang 石家庄",
				"冀B - Tangshan 唐山",
				"冀C - Qinhuangdao 秦皇岛",
				"冀D - Handan 邯郸",
				"冀E - Xingtai 形台",
				"冀F - Baoding 保定",
				"冀G - Zhangjiakou 张家口",
				"冀H - Chengde 承德",
				"冀J - Cangzhou 沧州",
				"冀R - Langfang 廊坊",
				"冀T - Hengshui 衡水",
				"黑 - Heilongjiang 黑龙江",
				"黑A - Harbin 哈尔滨",
				"黑B - Qiqihar 齐齐哈尔",
				"黑C - Mudanjiang 牡丹江",
				"黑D - Jiamusi 佳木斯",
				"黑E - Daqing 大庆",
				"黑F - Yichun 伊春",
				"黑G - Jixi 鸡西",
				"黑H - Hegang 鹤岗",
				"黑J - Shuangyashan 双鸭山",
				"黑K - Qitaihe 七台河",
				"黑L - Area of the Sungari River 松花江区",
				"黑M - Suihua 绥化",
				"黑N - Heihe 黑河",
				"黑P - Daxing'anling Prefecture 大兴安岭地区",
				"黑R - Farming system"
				"豫 - Henan 河南",
				"豫A - Zhengzhou 郑州",
				"豫B - Kaifeng 开封",
				"豫C - Luoyang 洛阳",
				"豫D - Pingdingshan 平顶山",
				"豫E - Anyang 安阳",
				"豫F - Hebi 鹤壁",
				"豫G - Xinxiang 新乡",
				"豫H - Jiaozuo 焦作",
				"豫J - Puyang 濮阳",
				"豫K - Xuchang 许昌",
				"豫L - Luohe 漯河",
				"豫M - Sanmenxia 三门峡",
				"豫N - Shangqiu 商丘",
				"豫P - Zhoukou 周口",
				"豫Q - Zhumadian 驻马店",
				"豫R - Nanyang 南阳",
				"豫S - Xinyang 信阳",
				"豫U - Jiyuan 济源",
				"鄂 - Hubei 湖北",
				"鄂A - Wuhan 武汉",
				"鄂B - Huangshi 黄石",
				"鄂C - Shiyan 十堰",
				"鄂D - Jingzhou 荆州",
				"鄂E - Yichang 宜昌",
				"鄂F - Xiangyang 襄阳",
				"鄂G - Ezhou 鄂州",
				"鄂H - Jingmen 荆门",
				"鄂J - Huanggang 黄冈",
				"鄂K - Xiaogan 孝感",
				"鄂L - Xianning 咸宁",
				"鄂M - Xiantao 仙桃",
				"鄂N - Qianjiang 潜江",
				"鄂P - Shennongjia 神农架林区",
				"鄂Q - Enshi Tujia and Miao Autonomous Prefecture 恩施土家族苗族自治州",
				"鄂R - Tianmen 天门",
				"鄂S - Suizhou 随州",
				"湘 - Hunan 湖南",
				"湘A - Changsha 长沙",
				"湘B - Zhuzhou 株洲",
				"湘C - Xiangtan 湘潭",
				"湘D - Hengyang 衡阳",
				"湘E - Shaoyang 邵阳",
				"湘F - Yueyang 岳阳",
				"湘G - Zhangjiajie 张家界",
				"湘H - Yiyang 益阳",
				"湘J - Changde 常德",
				"湘K - Loudi 娄底",
				"湘L - Chenzhou 郴州",
				"湘M - Yongzhou 永州",
				"湘N - Huaihua 怀化",
				"湘P - Xiangxi Tujia and Miao Autonomous Prefecture 湘西土家族苗族自治州",
				"苏 - Jiangsu 江苏",
				"苏A - Nanjing 南京",
				"苏B - Wuxi 无锡",
				"苏C - Xuzhou 徐州",
				"苏D - Changzhou 常州",
				"苏E, 苏U - Suzhou 苏州",
				"苏F - Nantong 南通",
				"苏G - Lianyungang 连云港",
				"苏H - Huai'an 淮安",
				"苏J - Yancheng 盐城",
				"苏K - Yangzhou 扬州",
				"苏L - Zhenjiang 镇江",
				"苏M - Taizhou 泰州",
				"苏N - Suqian 宿迁",
				"赣 - Jiangxi 江西",
				"赣A - Nanchang 南昌",
				"赣B - Ganzhou 赣州",
				"赣C - Yichun 宜春",
				"赣D - Ji'an 吉安",
				"赣E - Shangrao 上饶",
				"赣F - Fuzhou 抚州",
				"赣G - Jiujiang 九江",
				"赣H - Jingdezhen 景德镇",
				"赣J - Pingxiang 萍乡",
				"赣K - Xinyu 新余",
				"赣L - Yingtan 鹰潭",
				"吉 - Jilin 吉林",
				"吉A - Changchun 长春",
				"吉B - Jilin City 吉林市",
				"吉C - Siping 四平",
				"吉D - Liaoyuan 辽源",
				"吉E - Tonghua 通化",
				"吉F - Baishan 白山",
				"吉G - Baicheng 白城",
				"吉H - Yanbian Korean Autonomous Prefecture 延边州",
				"吉J - Songyuan 松原",
				"辽 - Liaoning 辽宁",
				"辽A - Shenyang 沈阳",
				"辽B - Dalian 大连",
				"辽C - Anshan 鞍山",
				"辽D - Fushun 抚顺",
				"辽E - Benxi 本溪",
				"辽F - Dandong 丹东",
				"辽G - Jinzhou 锦州",
				"辽H - Yingkou 营口",
				"辽J - Fuxin 阜新",
				"辽K - Liaoyang 辽阳",
				"辽L - Panjin 盘锦",
				"辽M - Tieling 铁岭",
				"辽N - Chaoyang 朝阳",
				"辽O - Police Vehicles 警车",
				"辽P - Huludao 葫芦岛",
				"青 - Qinghai 青海",
				"青A - Xining 西宁",
				"青B - Haidong 海东",
				"青C - Haibei Tibetan Autonomous Prefecture 海北藏族自治州",
				"青D - Huangnan Tibetan Autonomous Prefecture 黄南藏族自治州",
				"青E - Hainan Tibetan Autonomous Prefecture 海南藏族自治州",
				"青F - Golog Tibetan Autonomous Prefecture 果洛藏族自治州",
				"青G - Gyêgu Tibetan Autonomous Prefecture 玉树藏族自治州",
				"青H - Haixi Mongol and Tibetan Autonomous Prefecture 海西蒙古族藏族自治州",
				"陕 - Shaanxi 陕西",
				"陕A， 陕U - Xi'an 西安",
				"陕AV - Provincial-level agencies",
				"陕B - Tongchuan 铜川",
				"陕C - Baoji 宝鸡",
				"陕D - Xianyang 咸阳",
				"陕E - Weinan 渭南",
				"陕F - Hanzhong 汉中",
				"陕G - Ankang 安康",
				"陕H - Shangluo 商洛",
				"陕J - Yan'an 延安",
				"陕K - Yulin 榆林",
				"陕V - Yangling Gaoxin Agricultural Zone",
				"鲁 - Shandong 山东",
				"鲁A, 鲁W - Jinan 济南",
				"鲁B, 鲁U - Qingdao 青岛",
				"鲁C - Zibo 淄博",
				"鲁D - Zaozhuang 枣庄",
				"鲁E - Dongying 东营",
				"鲁F - Yantai 烟台",
				"鲁G, 鲁V - Weifang 潍坊",
				"鲁H - Jining 济宁",
				"鲁J - Tai'an 泰安",
				"鲁K - Weihai 威海",
				"鲁L - Rizhao 日照",
				"鲁M - Binzhou 滨州",
				"鲁N - Dezhou 德州",
				"鲁O - Police vehicles 警车",
				"鲁P - Liaocheng 聊城",
				"鲁Q - Linyi 临沂",
				"鲁R - Heze 菏泽",
				"鲁S - Laiwu 莱芜",
				"晋 - Shanxi 山西",
				"晋A - Taiyuan 太原",
				"晋B - Datong 大同",
				"晋C - Yangquan 阳泉",
				"晋D - Changzhi 长治",
				"晋E - Jincheng 晋城",
				"晋F - Shuozhou 朔州",
				"晋H - Xinzhou 忻州",
				"晋J - Lüliang 吕梁",
				"晋K - Jinzhong 晋中",
				"晋L - Linfen 临汾",
				"晋M - Yuncheng 运城",
				"川 - Sichuan 四川",
				"川A, 川G - Chengdu 成都",
				"川B - Mianyang 绵阳",
				"川C - Zigong 自贡",
				"川D - Panzhihua 攀枝花",
				"川E - Luzhou 泸州",
				"川F - Deyang 德阳",
				"川H - Guangyuan 广元",
				"川J - Suining 遂宁",
				"川K - Neijiang 内江",
				"川L - Leshan 乐山",
				"川M - Ziyang 资阳",
				"川N - Fuling 涪陵",
				"川O - Police vehicles 警车",
				"川P - Qianjiang Prefecture 黔江区",
				"川Q - Yibin 宜宾",
				"川R - Nanchong 南充",
				"川S - Dazhou 达州",
				"川T - Ya'an 雅安",
				"川U - Ngawa Tibetan and Qiang Autonomous Prefecture 阿坝藏族羌族自治州",
				"川V - Garzê Tibetan Autonomous Prefecture 甘孜藏族自治州",
				"川W - Liangshan Yi Autonomous Prefecture 凉山彝族自治州",
				"川X - Guang'an 广安",
				"川Y - Bazhong 巴中",
				"川Z - Meishan 眉山",
				"云 - Yunnan 云南",
				"云A - Kunming 昆明",
				"云B - Dongchuan 东川",
				"云C - Zhaotong 昭通",
				"云D - Qujing 曲靖",
				"云E - Chuxiong Yi Autonomous Prefecture 楚雄彝族自治州",
				"云F - Yuxi 玉溪",
				"云G - Honghe Hani and Yi Autonomous Prefecture 红河哈尼族彝族自治州",
				"云H - Wenshan Zhuang and Miao Autonomous Prefecture 文山壮族苗族自治州",
				"云J - Pu'er 普洱",
				"云K - Xishuangbanna Dai Autonomous Prefecture 西双版纳泰族自治州",
				"云L - Dali Bai Autonomous Prefecture 大理白族自治州",
				"云M - Baoshan 保山",
				"云N - Dehong Dai and Jingpo Autonomous Prefecture 德宏泰族景颇族自治州",
				"云P - Lijiang 丽江",
				"云Q - Nujiang Lisu Autonomous Prefecture 怒江傈僳族自治州",
				"云R - Diqing Tibetan Autonomous Prefecture 迪慶藏族自治州",
				"云S - Lincang 临沧",
				"浙 - Zhejiang 浙江",
				"浙A - Hangzhou 杭州",
				"浙B - Ningbo 宁波",
				"浙C - Wenzhou 温州",
				"浙D - Shaoxing 绍兴",
				"浙E - Huzhou 湖州",
				"浙F - Jiaxing 嘉兴",
				"浙G - Jinhua 金华",
				"浙H - Quzhou 衢州",
				"浙J - Taizhou 台州",
				"浙K - Lishui 丽水",
				"浙L - Zhoushan 舟山",
				"浙O - Foreign enterprises 外国公司",
				"桂 - Guangxi 广西",
				"桂A - Nanning 南宁",
				"桂B - Liuzhou 柳州",
				"桂C, 桂H - Guilin 桂林",
				"桂D - Wuzhou 梧州",
				"桂E - Beihai 北海",
				"桂F - Chongzuo 崇左",
				"桂G - Laibin 来宾",
				"桂J - Hezhou 贺州",
				"桂K - Yulin 玉林",
				"桂L - Baise 白色",
				"桂M - Hechi 河池",
				"桂N - Qinzhou 钦州",
				"桂P - Fangchenggang 防城港",
				"桂R - Guigang 贵港",
				"蒙 - Inner Mongolia 内蒙古",
				"蒙A - Hohhot 呼和浩特",
				"蒙B - Baotou 包头",
				"蒙C - Wuhai 乌海",
				"蒙D - Chifeng 赤峰",
				"蒙E - Hulunbuir 呼伦贝尔",
				"蒙F - Hinggan League 兴安盟",
				"蒙G - Tongliao 通辽",
				"蒙H - Xilin Gol League 锡林郭勒盟",
				"蒙J - Ulaan Chab 乌兰察布",
				"蒙K - Ordos 鄂尔多斯",
				"蒙L - Bayan Nur 巴彦淖尔",
				"蒙M - Alxa League 阿拉善盟",
				"宁 - Ningxia 宁夏",
				"宁A - Yinchuan 银川",
				"宁B - Shizuishan 石嘴山",
				"宁C - Wuzhong 吴忠",
				"宁D - Guyuan 固原",
				"宁E - Zhongwei 中卫",
				"藏 - Tibet 西藏",
				"藏A - Lhasa 城关区",
				"藏B - Qamdo 昌都",
				"藏C - Shannan Prefecture 山南",
				"藏D - Xigazê 日喀则",
				"藏E - Naqu Prefecture 那曲",
				"藏F - Ngari Prefecture 阿里地区",
				"藏G - Nyingchi 林芝",
				"新 - Xinjiang 新疆",
				"新A - Ürümqi 乌鲁木齐",
				"新B - Changji Hui Autonomous Prefecture 昌吉",
				"新C - Shihezi 石河子",
				"新D - Kuitun 奎屯",
				"新E - Börtala Mongol Autonomous Prefecture 博尔塔拉蒙古族自治州",
				"新F - Ili Kazakh Autonomous Prefecture 伊犁哈萨克自治州",
				"新G - Qoqek 塔城",
				"新H - Altay 阿勒泰",
				"新J - Karamay 克拉玛依",
				"新K - Turpan 吐鲁番",
				"新L - Hami 哈密",
				"新M - Bayin'gholin Mongol Autonomous Prefecture 巴音郭楞蒙古自治州",
				"新N - Aksu Prefecture 阿克苏地区",
				"新P - Kizilsu Kirghiz Autonomous Prefecture 克孜勒苏柯尔克孜自治州",
				"新Q - Kashgar 喀什",
				"新R - Hotan 和田",
				"新S - Kunyu 昆玉"
			],
			[
				"AG - Agrigento",
				"AQ - L'Aquila",
				"BG - Bergamo",
				"BR - Brindisi",
				"CB - Campobasso",
				"CN - Cuneo",
				"CZ - Catanzaro",
				"FI - Firenze",
				"GR - Grosseto",
				"LE - Lecce",
				"MB - Monza e Brianza",
				"MO - Modena",
				"NU - Nuoro",
				"PC - Piacenza",
				"PN - Pordenone",
				"PV - Pavia",
				"RG - Ragusa",
				"SA - Salerno",
				"SS - Sassari",
				"TO - Torino",
				"UD - Udine",
				"VI - Vicenza",
				"AL - Alessandria",
				"AR - Arezzo",
				"BI - Biella",
				"BS - Brescia",
				"CE - Caserta",
				"CO - Como",
				"EN - Enna",
				"FM - Fermo",
				"IM - Imperia",
				"LI - Livorno",
				"MC - Macerata",
				"MS - Massa-Carrara",
				"OG - Ogliastra",
				"PD - Padova",
				"PO - Prato",
				"PZ - Potenza",
				"RI - Rieti",
				"SI - Siena",
				"SV - Savona",
				"TP - Trapani",
				"VA - Varese",
				"VR - Verona",
				"AP - Ascoli Piceno",
				"BA - Bari",
				"BO - Bologna",
				"CA - Cagliari",
				"CL - Caltanissetta",
				"CT - Catania",
				"FG - Foggia",
				"GO - Gorizia",
				"LC - Lecco",
				"LU - Lucca",
				"MN - Mantova",
				"NO - Novara",
				"PA - Palermo",
				"PI - Pisa",
				"PU - Pesaro-Urbino",
				"RE - Reggio Emilia",
				"Roma - Roma",
				"SR - Siracusa",
				"TN - Trento",
				"TV - Treviso",
				"VE - Venezia",
				"VV - Vibo Valentia",
				"AO - Aosta",
				"AV - Avellino",
				"BN - Benevento",
				"BZ - Bolzano",
				"CI - Carbonia-Iglesias",
				"CS - Cosenza",
				"FE - Ferrara",
				"GE - Genova",
				"KR - Crotone",
				"LT - Latina",
				"MI - Milano",
				"NA - Napoli",
				"OT - Olbia-Tempio",
				"PG - Perugia",
				"PT - Pistoia",
				"RC - Reggio Calabria",
				"RO - Rovigo",
				"SP - La Spezia",
				"TE - Teramo",
				"TS - Trieste",
				"VC - Vercelli",
				"VT - Viterbo",
				"AN - Ancona",
				"AT - Asti",
				"BL - Belluno",
				"BT - Barletta-Andria-Trani",
				"CH - Chieti",
				"CR - Cremona",
				"FC - Forlì-Cesena",
				"FR - Frosinone",
				"IS - Isernia",
				"LO - Lodi",
				"ME - Messina",
				"MT - Matera",
				"OR - Oristano",
				"PE - Pescara",
				"PR - Parma",
				"RA - Ravenna",
				"RN - Rimini",
				"SO - Sondrio",
				"TA - Taranto",
				"TR - Terni",
				"VB - Verbania",
				"VS - Medio Campidano"
			],
			[
				"0-1 - Bundespräsident",
				"0-2 - Bundeskanzler",
				"0-3 - Außenminister",
				"0-4 - Erster Staatssekretär im Auswärtigen Amt",
				"1-1 - Bundestagspräsident",
				"10 - Vatikanstadt",
				"11 - Ägypten",
				"12 - Angola",
				"13 - Albanien",
				"14 - Äthiopien",
				"15 - Afghanistan",
				"16 - Algerien",
				"17 - Vereinigte Staaten",
				"18 - Argentinien",
				"19 - Australien",
				"20 - Bangladesch",
				"21 - Belgien",
				"22 - Brunei",
				"23 - Bulgarien",
				"24 - Myanmar",
				"25 - Bolivien",
				"26 - Brasilien",
				"27 - Burundi",
				"28 - Chile",
				"29 - Volksrepublik China",
				"30 - Costa Rica",
				"31 - Weißrussland",
				"32 - Bosnien und Herzegowina",
				"33 - Äquatorialguinea",
				"34 - Dänemark",
				"35 - Benin",
				"36 - Dominikanische Republik",
				"37 - Ecuador",
				"38 - Elfenbeinküste",
				"39 - El Salvador",
				"40 - Kosovo",
				"41 - Estland",
				"42 - Liechtenstein",
				"43 - Montenegro",
				"44 - Finnland",
				"45 - Frankreich",
				"46 - Gabun",
				"47 - Ghana",
				"48 - Griechenland",
				"49 - Vereinigtes Königreich",
				"50 - Guatemala",
				"51 - Guinea",
				"52 - Lettland",
				"53 - Litauen",
				"54 - Haiti",
				"55 - Honduras",
				"56 - Indien",
				"57 - Indonesien",
				"58 - Irak",
				"59 - Iran",
				"60 - Irland",
				"61 - Island",
				"62 - Laos",
				"63 - Kap Verde",
				"64 - Israel",
				"65 - Italien",
				"66 - Jamaika",
				"67 - Japan",
				"68 - Jemen",
				"69 - Jordanien",
				"70 - Serbien",
				"71 - Kuwait",
				"72 - Kuba",
				"73 - Katar",
				"74 - Kamerun",
				"75 - Kanada",
				"76 - Kenia",
				"77 - Kolumbien",
				"78 - Republik Kongo",
				"79 - Südkorea",
				"80 - Libanon",
				"81 - Liberia",
				"82 - Libyen",
				"83 - Lesotho",
				"84 - Luxemburg",
				"85 - Madagaskar",
				"86 - Malawi",
				"87 - Malaysia",
				"88 - Mali",
				"89 - Marokko",
				"90 - Mauretanien",
				"91 - Mexiko",
				"92 - Malta",
				"93 - Monaco",
				"94 - Nepal",
				"95 - Neuseeland",
				"96 - Nicaragua",
				"97 - Niederlande",
				"98 - Niger",
				"99 - Nigeria",
				"100 - Norwegen",
				"101 - Mongolei",
				"102 - Mosambik",
				"103 - Oman",
				"104 - Burkina Faso",
				"105 - Österreich",
				"106 - Pakistan",
				"107 - Panama",
				"108 - Paraguay",
				"109 - Peru",
				"110 - Philippinen",
				"111 - Polen",
				"112 - Portugal",
				"113 - Papua-Neuguinea",
				"114 - Namibia",
				"115 - Ruanda",
				"116 - Rumänien",
				"117 - Sambia",
				"118 - Saudi-Arabien",
				"119 - Schweden",
				"120 - Schweiz",
				"121 - Senegal",
				"122 - Sierra Leone",
				"123 - Singapur",
				"124 - Simbabwe",
				"125 - Somalia",
				"126 - Spanien",
				"127 - Sri Lanka",
				"128 - Sudan",
				"129 - Südafrika",
				"130 - Syrien",
				"131 - Tansania",
				"132 - Thailand",
				"133 - Togo",
				"134 - Tonga",
				"135 - Tschechien",
				"136 - Tschad",
				"137 - Türkei",
				"138 - Tunesien",
				"139 - Uganda",
				"140 - Russland",
				"141 - Uruguay",
				"142 - Ungarn",
				"143 - Ukraine",
				"144 - Grenada",
				"146 - Venezuela",
				"147 - Vietnam",
				"148 - Vereinigte Arabische Emirate",
				"151 - Demokratische Republik Kongo",
				"152 - Zentralafrikanische Republik",
				"153 - Zypern",
				"154 - Kroatien",
				"155 - Slowenien",
				"156 - Aserbaidschan",
				"157 - Slowakei",
				"158 - Kasachstan",
				"159 - Mazedonien",
				"160 - Usbekistan",
				"161 - Eritrea",
				"162 - Georgien",
				"163 - Tadschikistan",
				"164 - Bahrain",
				"165 - Kambodscha",
				"166 - Armenien",
				"167 - Kirgisistan",
				"168 - Moldawien",
				"169 - Turkmenistan",
				"200 - Mauritius",
				"201 - Nordkorea",
				"202 - Dschibuti",
				"203 - Guinea-Bissau",
				"204 - Südsudan",
				"205 - Botswana"
			],
			[
				"A - Stadt/Landkreis Augsburg; Polizeipräsidium Schwaben Nord",
				"AA - Ostalbkreis",
				"AB - Stadt/Landkreis Aschaffenburg",
				"ABG - Landkreis Altenburger Land",
				"ABI - Landkreis Anhalt-Bitterfeld",
				"AC - Städteregion Aachen",
				"AE - Vogtlandkreis",
				"AH - Kreis Borken",
				"AIB - Landkreis München/Rosenheim",
				"AIC - Landkreis Aichach-Friedberg",
				"AK - Landkreis Altenkirchen (Westerwald)",
				"ALF - Landkreis Hildesheim",
				"ALZ - Landkreis Aschaffenburg",
				"AM - Stadt Amberg",
				"AN - Stadt/Landkreis Ansbach",
				"ANA - Erzgebirgskreis",
				"ANG - Landkreis Uckermark",
				"ANK - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
				"AÖ - Landkreis Altötting",
				"AP - Landkreis Weimarer Land",
				"APD - Landkreis Weimarer Land",
				"ARN - Ilm-Kreis",
				"ART - Kyffhäuserkreis",
				"AS - Landkreis Amberg-Sulzbach",
				"ASL - Salzlandkreis",
				"ASZ - Erzgebirgskreis",
				"AT - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"AU - Erzgebirgskreis",
				"AUR - Landkreis Aurich",
				"AW - Landkreis Ahrweiler",
				"AZ - Landkreis Alzey-Worms",
				"AZE - Landkreis Anhalt-Bitterfeld",
				"B - Stadt Berlin; Senat, Abgeordnetenhaus, Diplomaten",
				"BA - Stadt/Landkreis Bamberg; Bayerisches Bereitschaftspolizeipräsidium",
				"BAD - Stadt Baden-Baden",
				"BAR - Landkreis Barnim",
				"BB - Landkreis Böblingen",
				"BBG - Salzlandkreis",
				"BBL - Brandenburg, Landesregierung, Landtag, Polizei",
				"BC - Landkreis Biberach",
				"BCH - Neckar-Odenwald-Kreis",
				"BD - Deutscher Bundestag, Bundesrat, Bundespräsidialamt, Bundesregierung, Bundesministerien, Bundesfinanzverwaltung, Bundesverfassungsgericht",
				"BE - Kreis Warendorf",
				"BED - Landkreis Mittelsachsen",
				"BER - Landkreis Barnim",
				"BF - Kreis Steinfurt",
				"BGD - Landkreis Berchtesgadener Land",
				"BGL - Landkreis Berchtesgadener Land",
				"BH - Ortenaukreis; Landkreis Rastatt",
				"BI - Stadt Bielefeld",
				"BID - Landkreis Marburg-Biedenkopf",
				"BIN - Landkreis Mainz-Bingen",
				"BIR - Landkreis Birkenfeld",
				"BIT - Eifelkreis Bitburg-Prüm",
				"BIW - Landkreis Bautzen",
				"BK - Rems-Murr-Kreis; Landkreis Börde",
				"BKS - Landkreis Bernkastel-Wittlich",
				"BL - Zollernalbkreis",
				"BLB - Kreis Siegen-Wittgenstein",
				"BLK - Burgenlandkreis",
				"BM - Rhein-Erft-Kreis",
				"BN - Stadt Bonn; Diplomaten",
				"BNA - Landkreis Leipzig",
				"BO - Stadt Bochum",
				"BÖ - Landkreis Börde",
				"BOH - Kreis Borken",
				"BOR - Kreis Borken",
				"BOT - Stadt Bottrop",
				"BP - Bundespolizei",
				"BRA - Landkreis Wesermarsch",
				"BRB - Stadt Brandenburg an der Havel",
				"BRG - Landkreis Jerichower Land",
				"BRK - Landkreis Bad Kissingen",
				"BRL - Landkreis Goslar",
				"BRV - Landkreis Rotenburg (Wümme)",
				"BS - Stadt/Polizeidirektion Braunschweig",
				"BT - Stadt/Landkreis Bayreuth; Polizeipräsidium Oberfranken",
				"BTF - Landkreis Anhalt-Bitterfeld",
				"BÜD - Wetteraukreis",
				"BUL - Landkreis Amberg-Sulzbach/Schwandorf",
				"BÜR - Kreis Paderborn",
				"BÜS - Gemeinde Büsingen am Hochrhein",
				"BÜZ - Landkreis Rostock",
				"BW - Wasserstraßen- und Schifffahrtsverwaltung des Bundes",
				"BWL - Baden-Württemberg, Landesregierung, Landtag, Polizei",
				"BYL - Bayern, Landesregierung, Landtag",
				"BZ - Landkreis Bautzen",
				"C - Stadt Chemnitz",
				"CA - Landkreis Oberspreewald-Lausitz",
				"CAS - Kreis Recklinghausen",
				"CB - Stadt Cottbus",
				"CE - Landkreis Celle",
				"CHA - Landkreis Cham",
				"CLP - Landkreis Cloppenburg",
				"CLZ - Landkreis Goslar",
				"CO - Stadt/Landkreis Coburg",
				"COC - Landkreis Cochem-Zell",
				"COE - Kreis Coesfeld",
				"CR - Landkreis Schwäbisch Hall",
				"CUX - Landkreis Cuxhaven",
				"CW - Landkreis Calw",
				"D - Stadt Düsseldorf",
				"DA - Landkreis Darmstadt-Dieburg; Stadt Darmstadt",
				"DAH - Landkreis Dachau",
				"DAN - Landkreis Lüchow-Dannenberg",
				"DAU - Landkreis Vulkaneifel",
				"DBR - Landkreis Rostock",
				"DD - Stadt Dresden; Polizei Sachsen",
				"DE - Stadt Dessau-Roßlau",
				"DEG - Landkreis Deggendorf",
				"DEL - Stadt Delmenhorst",
				"DGF - Landkreis Dingolfing-Landau",
				"DH - Landkreis Diepholz",
				"DI - Landkreis Darmstadt-Dieburg",
				"DIL - Lahn-Dill-Kreis ohne die Stadt Wetzlar",
				"DIN - Kreis Wesel",
				"DIZ - Rhein-Lahn-Kreis",
				"DKB - Landkreis Ansbach",
				"DL - Landkreis Mittelsachsen",
				"DLG - Landkreis Dillingen an der Donau",
				"DM - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"DN - Kreis Düren",
				"DO - Stadt Dortmund",
				"DON - Landkreis Donau-Ries",
				"DU - Stadt Duisburg",
				"DUD - Landkreis Göttingen ohne die Stadt Göttingen",
				"DÜW - Landkreis Bad Dürkheim",
				"DW - Landkreis Sächsische Schweiz-Osterzgebirge",
				"DZ - Landkreis Nordsachsen",
				"E - Stadt Essen",
				"EA - Stadt Eisenach",
				"EB - Landkreis Nordsachsen",
				"EBE - Landkreis Ebersberg",
				"EBN - Landkreis Haßberge",
				"EBS - Landkreis Bayreuth/Forchheim/Kulmbach",
				"ECK - Kreis Rendsburg-Eckernförde",
				"ED - Landkreis Erding",
				"EE - Landkreis Elbe-Elster",
				"EF - Stadt Erfurt; Thüringer Polizei",
				"EG - Landkreis Rottal-Inn",
				"EI - Landkreis Eichstätt",
				"EIC - Landkreis Eichsfeld",
				"EIL - Landkreis Mansfeld-Südharz",
				"EIN - Landkreis Northeim",
				"EIS - Saale-Holzland-Kreis",
				"EL - Landkreis Emsland",
				"EM - Landkreis Emmendingen",
				"EMD - Stadt Emden",
				"EMS - Rhein-Lahn-Kreis",
				"EN - Ennepe-Ruhr-Kreis",
				"ER - Stadt Erlangen",
				"ERB - Odenwaldkreis",
				"ERH - Landkreis Erlangen-Höchstadt",
				"ERK - Kreis Heinsberg",
				"ERZ - Erzgebirgskreis",
				"ES - Landkreis Esslingen",
				"ESB - Landkreis Amberg-Sulzbach/Bayreuth/Neustadt an der Waldnaab/Nürnberger Land",
				"ESW - Werra-Meißner-Kreis",
				"EU - Kreis Euskirchen",
				"EW - Landkreis Barnim",
				"F - Stadt Frankfurt am Main",
				"FB - Wetteraukreis",
				"FD - Landkreis Fulda",
				"FDB - Landkreis Aichach-Friedberg",
				"FDS - Landkreis Freudenstadt",
				"FEU - Landkreis Ansbach",
				"FF - Stadt Frankfurt (Oder)",
				"FFB - Landkreis Fürstenfeldbruck",
				"FG - Landkreis Mittelsachsen",
				"FI - Landkreis Elbe-Elster",
				"FKB - Landkreis Waldeck-Frankenberg",
				"FL - Stadt Flensburg",
				"FLÖ - Landkreis Mittelsachsen",
				"FN - Bodenseekreis",
				"FO - Landkreis Forchheim",
				"FOR - Landkreis Spree-Neiße",
				"FR - Stadt Freiburg im Breisgau; Landkreis Breisgau-Hochschwarzwald",
				"FRG - Landkreis Freyung-Grafenau",
				"FRI - Landkreis Friesland",
				"FRW - Landkreis Märkisch-Oderland",
				"FS - Landkreis Freising",
				"FT - Stadt Frankenthal (Pfalz)",
				"FTL - Landkreis Sächsische Schweiz-Osterzgebirge",
				"FÜ - Stadt/Landkreis Fürth",
				"FÜS - Landkreis Ostallgäu",
				"FZ - Schwalm-Eder-Kreis",
				"G - Stadt Gera",
				"GA - Altmarkkreis Salzwedel",
				"GAN - Landkreis Northeim",
				"GAP - Landkreis Garmisch-Partenkirchen",
				"GC - Landkreis Zwickau",
				"GD - Ostalbkreis",
				"GDB - Landkreis Nordwestmecklenburg",
				"GE - Stadt Gelsenkirchen",
				"GEL - Kreis Kleve",
				"GEO - Landkreis Haßberge/Schweinfurt",
				"GER - Landkreis Germersheim",
				"GF - Landkreis Gifhorn",
				"GG - Kreis Groß-Gerau",
				"GHA - Landkreis Leipzig",
				"GHC - Landkreis Wittenberg",
				"GI - Landkreis Gießen",
				"GK - Kreis Heinsberg",
				"GL - Rheinisch-Bergischer Kreis",
				"GLA - Kreis Recklinghausen",
				"GM - Oberbergischer Kreis",
				"GMN - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
				"GN - Main-Kinzig-Kreis ohne die Stadt Hanau",
				"GNT - Landkreis Jerichower Land",
				"GÖ - Stadt/Landkreis/Polizeidirektion Göttingen",
				"GOA - Rhein-Hunsrück-Kreis",
				"GOH - Rhein-Lahn-Kreis",
				"GP - Landkreis Göppingen",
				"GR - Landkreis Görlitz",
				"GRA - Landkreis Freyung-Grafenau",
				"GRH - Landkreis Meißen",
				"GRI - Landkreis Rottal-Inn",
				"GRM - Landkreis Leipzig",
				"GRZ - Landkreis Greiz",
				"GS - Landkreis Goslar",
				"GT - Kreis Gütersloh",
				"GTH - Landkreis Gotha",
				"GÜ - Landkreis Rostock",
				"GUB - Landkreis Spree-Neiße",
				"GUN - Landkreis Weißenburg-Gunzenhausen",
				"GV - Rhein-Kreis Neuss",
				"GVM - Landkreis Nordwestmecklenburg",
				"GW - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
				"GZ - Landkreis Günzburg",
				"H - Region/Stadt Hannover; Polizeidirektion Niedersachsen (Zentrale)/Hannover",
				"HA - Stadt Hagen",
				"HAB - Landkreis Bad Kissingen",
				"HAL - Stadt Halle (Saale)",
				"HAM - Stadt Hamm",
				"HAS - Landkreis Haßberge",
				"HB - Stadt Bremen/Bremerhaven; Senat, Bürgerschaft",
				"HBN - Landkreis Hildburghausen",
				"HBS - Landkreis Harz",
				"HC - Landkreis Mittelsachsen",
				"HCH - Zollernalbkreis",
				"HD - Stadt Heidelberg; Rhein-Neckar-Kreis",
				"HDH - Landkreis Heidenheim",
				"HDL - Landkreis Börde",
				"HE - Landkreis Helmstedt",
				"HEB - Landkreis Nürnberger Land",
				"HEF - Landkreis Hersfeld-Rotenburg",
				"HEI - Kreis Dithmarschen",
				"HEL - Hessen, Landesregierung, Landtag",
				"HER - Stadt Herne",
				"HET - Landkreis Mansfeld-Südharz",
				"HF - Kreis Herford",
				"HG - Hochtaunuskreis",
				"HGN - Landkreis Ludwigslust-Parchim",
				"HGW - Stadt Greifswald",
				"HH - Freie und Hansestadt Hamburg, Senat, Bürgerschaft",
				"HHM - Burgenlandkreis",
				"HI - Landkreis Hildesheim",
				"HIG - Landkreis Eichsfeld",
				"HIP - Landkreis Roth",
				"HK - Landkreis Heidekreis",
				"HL - Stadt Lübeck",
				"HM - Landkreis Hameln-Pyrmont",
				"HMÜ - Landkreis Göttingen ohne die Stadt Göttingen",
				"HN - Stadt/Landkreis Heilbronn",
				"HO - Stadt/Landkreis Hof",
				"HOG - Landkreis Kassel",
				"HOH - Landkreis Haßberge",
				"HOL - Landkreis Holzminden",
				"HOM - Saarpfalz-Kreis ohne die Stadt St. Ingbert",
				"HOR - Landkreis Freudenstadt",
				"HÖS - Landkreis Erlangen-Höchstadt",
				"HOT - Landkreis Zwickau",
				"HP - Kreis Bergstraße",
				"HR - Schwalm-Eder-Kreis",
				"HRO - Stadt Rostock",
				"HS - Kreis Heinsberg",
				"HSK - Hochsauerlandkreis",
				"HST - Stadt Stralsund",
				"HU - Stadt Hanau; Main-Kinzig-Kreis",
				"HV - Landkreis Stendal",
				"HVL - Landkreis Havelland",
				"HWI - Stadt Wismar",
				"HX - Kreis Höxter",
				"HY - Landkreis Bautzen",
				"HZ - Landkreis Harz",
				"IGB - Stadt St. Ingbert",
				"IK - Ilm-Kreis",
				"IL - Ilm-Kreis",
				"ILL - Landkreis Neu-Ulm",
				"IN - Stadt Ingolstadt; Polizeipräsidium Oberbayern Nord",
				"IZ - Kreis Steinburg",
				"J - Stadt Jena",
				"JE - Landkreis Wittenberg",
				"JL - Landkreis Jerichower Land",
				"JÜL - Kreis Düren",
				"K - Stadt Köln",
				"KA - Stadt/Landkreis Karlsruhe",
				"KB - Landkreis Waldeck-Frankenberg",
				"KC - Landkreis Kronach",
				"KE - Stadt Kempten (Allgäu); Polizeipräsidium Schwaben Süd/West",
				"KEH - Landkreis Kelheim",
				"KEL - Ortenaukreis",
				"KEM - Landkreis Bayreuth/Tirschenreuth",
				"KF - Stadt Kaufbeuren",
				"KG - Landkreis Bad Kissingen",
				"KH - Landkreis Bad Kreuznach",
				"KI - Stadt Kiel",
				"KIB - Donnersbergkreis",
				"KK - Kreis Viersen",
				"KL - Stadt/Landkreis Kaiserslautern",
				"KLE - Kreis Kleve",
				"KLZ - Altmarkkreis Salzwedel",
				"KM - Landkreis Bautzen",
				"KN - Landkreis Konstanz ohne die Gemeinde Büsingen am Hochrhein",
				"KO - Stadt Koblenz",
				"KÖN - Landkreis Rhön-Grabfeld",
				"KÖT - Landkreis Anhalt-Bitterfeld",
				"KÖZ - Landkreis Cham",
				"KR - Stadt Krefeld",
				"KRU - Landkreis Günzburg",
				"KS - Stadt/Landkreis Kassel",
				"KT - Landkreis Kitzingen",
				"KU - Landkreis Kulmbach",
				"KÜN - Hohenlohekreis",
				"KUS - Landkreis Kusel",
				"KW - Landkreis Dahme-Spreewald",
				"KY - Landkreis Ostprignitz-Ruppin",
				"KYF - Kyffhäuserkreis",
				"L - Stadt/Landkreis Leipzig",
				"LA - Stadt/Landkreis Landshut",
				"LAN - Landkreis Dingolfing-Landau",
				"LAU - Landkreis Nürnberger Land",
				"LB - Landkreis Ludwigsburg",
				"LBS - Saale-Orla-Kreis",
				"LBZ - Landkreis Ludwigslust-Parchim",
				"LC - Landkreis Dahme-Spreewald",
				"LD - Stadt Landau in der Pfalz",
				"LDK - Lahn-Dill-Kreis ohne die Stadt Wetzlar",
				"LDS - Landkreis Dahme-Spreewald",
				"LEO - Landkreis Böblingen",
				"LER - Landkreis Leer",
				"LEV - Stadt Leverkusen",
				"LF - Landkreis Altötting/Berchtesgadener Land/Traunstein",
				"LG - Landkreis/Polizeidirektion Lüneburg",
				"LH - Kreis Coesfeld/Unna",
				"LI - Landkreis Lindau (Bodensee)",
				"LIB - Landkreis Elbe-Elster",
				"LIF - Landkreis Lichtenfels",
				"LIP - Kreis Lippe",
				"LL - Landkreis Landsberg am Lech",
				"LM - Landkreis Limburg-Weilburg",
				"LN - Landkreis Dahme-Spreewald",
				"LÖ - Landkreis Lörrach",
				"LÖB - Landkreis Görlitz",
				"LOS - Landkreis Oder-Spree",
				"LP - Kreis Soest",
				"LR - Ortenaukreis",
				"LRO - Landkreis Rostock",
				"LSA - Sachsen-Anhalt, Landesregierung, Landtag, Polizei",
				"LSN - Sachsen, Landesregierung, Landtag",
				"LSZ - Unstrut-Hainich-Kreis",
				"LU - Stadt Ludwigshafen am Rhein",
				"LÜN - Kreis Unna",
				"LUP - Landkreis Ludwigslust-Parchim",
				"LWL - Landkreis Ludwigslust-Parchim",
				"M - Stadt/Landkreis/Polizeipräsidum München",
				"MA - Stadt Mannheim",
				"MAB - Erzgebirgskreis",
				"MAI - Landkreis Kelheim/Landshut",
				"MAK - Landkreis Wunsiedel im Fichtelgebirge",
				"MAL - Landkreis Landshut",
				"MB - Landkreis Miesbach",
				"MC - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"MD - Stadt Magdeburg",
				"ME - Kreis Mettmann",
				"MED - Kreis Dithmarschen",
				"MEG - Schwalm-Eder-Kreis",
				"MEI - Landkreis Meißen",
				"MEK - Erzgebirgskreis",
				"MER - Saalekreis",
				"MET - Landkreis Rhön-Grabfeld",
				"MG - Stadt Mönchengladbach",
				"MGH - Main-Tauber-Kreis",
				"MGN - Landkreis Schmalkalden-Meiningen",
				"MH - Stadt Mülheim an der Ruhr",
				"MHL - Unstrut-Hainich-Kreis",
				"MI - Kreis Minden-Lübbecke",
				"MIL - Landkreis Miltenberg",
				"MK - Märkischer Kreis",
				"MKK - Main-Kinzig-Kreis ohne die Stadt Hanau",
				"ML - Landkreis Mansfeld-Südharz",
				"MM - Stadt Memmingen",
				"MN - Landkreis Unterallgäu",
				"MO - Kreis Wesel",
				"MOD - Landkreis Ostallgäu",
				"MOL - Landkreis Märkisch-Oderland",
				"MON - Städteregion Aachen; Kreis Düren",
				"MOS - Neckar-Odenwald-Kreis",
				"MQ - Saalekreis",
				"MR - Landkreis Marburg-Biedenkopf",
				"MS - Stadt Münster",
				"MSE - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"MSH - Landkreis Mansfeld-Südharz",
				"MSP - Landkreis Main-Spessart",
				"MST - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"MTK - Main-Taunus-Kreis",
				"MTL - Landkreis Leipzig",
				"MÜ - Landkreis Mühldorf am Inn",
				"MÜB - Landkreis Bayreuth/Hof",
				"MÜR - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"MVL - Mecklenburg-Vorpommern, Landesregierung, Landtag, Polizei",
				"MW - Landkreis Mittelsachsen",
				"MY - Landkreis Mayen-Koblenz",
				"MYK - Landkreis Mayen-Koblenz",
				"MZ - Stadt Mainz; Landkreis Mainz-Bingen",
				"MZG - Landkreis Merzig-Wadern",
				"N - Stadt Nürnberg; Landkreis Nürnberger Land; Polizeipräsidum Mittelfranken",
				"NAB - Landkreis Amberg-Sulzbach/Schwandorf",
				"NAI - Landkreis Hof",
				"NAU - Landkreis Havelland",
				"NB - Stadt Neubrandenburg",
				"ND - Landkreis Neuburg-Schrobenhausen",
				"NDH - Landkreis Nordhausen",
				"NE - Rhein-Kreis Neuss",
				"NEA - Landkreis Neustadt an der Aisch-Bad Windsheim",
				"NEB - Burgenlandkreis",
				"NEC - Stadt/Landkreis Coburg",
				"NEN - Landkreis Schwandorf",
				"NES - Landkreis Rhön-Grabfeld",
				"NEW - Landkreis Neustadt an der Waldnaab",
				"NF - Kreis Nordfriesland",
				"NH - Landkreis Sonneberg",
				"NI - Landkreis Nienburg/Weser",
				"NK - Landkreis Neunkirchen",
				"NL - Niedersachsen, Landesregierung, Landtag",
				"NM - Landkreis Neumarkt in der Oberpfalz",
				"NMB - Burgenlandkreis",
				"NMS - Stadt Neumünster",
				"NÖ - Landkreis Donau-Ries",
				"NOH - Landkreis Grafschaft Bentheim",
				"NOL - Landkreis Görlitz",
				"NOM - Landkreis Northeim",
				"NOR - Landkreis Aurich",
				"NP - Landkreis Ostprignitz-Ruppin",
				"NR - Landkreis Neuwied",
				"NRW - Nordrhein-Westfalen, Landesregierung, Landtag, Polizei",
				"NT - Landkreis Esslingen",
				"NU - Landkreis Neu-Ulm",
				"NVP - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
				"NW - Stadt Neustadt an der Weinstraße",
				"NWM - Landkreis Nordwestmecklenburg ohne die Stadt Wismar",
				"NY - Landkreis Görlitz",
				"NZ - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"OA - Landkreis Oberallgäu",
				"OAL - Landkreis Ostallgäu",
				"OB - Stadt Oberhausen",
				"OBG - Landkreis Stendal",
				"OC - Landkreis Börde",
				"OCH - Landkreis Würzburg",
				"OD - Kreis Stormarn",
				"OE - Kreis Olpe",
				"OF - Landkreis Offenbach; Stadt Offenbach am Main",
				"OG - Ortenaukreis",
				"OH - Kreis Ostholstein",
				"OHA - Landkreis Göttingen",
				"ÖHR - Hohenlohekreis",
				"OHV - Landkreis Oberhavel",
				"OHZ - Landkreis Osterholz",
				"OK - Landkreis Börde",
				"OL - Stadt/Landkreis/Polizeidirektion Oldenburg",
				"OP - Stadt Leverkusen",
				"OPR - Landkreis Ostprignitz-Ruppin",
				"OS - Stadt/Landkreis/Polizeidirektion Osnabrück",
				"OSL - Landkreis Oberspreewald-Lausitz",
				"OVI - Landkreis Schwandorf",
				"OVL - Vogtlandkreis",
				"OZ - Landkreis Nordsachsen",
				"P - Stadt Potsdam",
				"PA - Stadt/Landkreis Passau",
				"PAF - Landkreis Pfaffenhofen an der Ilm",
				"PAN - Landkreis Rottal-Inn",
				"PAR - Landkreis Kelheim/Neumarkt in der Oberpfalz",
				"PB - Kreis Paderborn",
				"PCH - Landkreis Ludwigslust-Parchim",
				"PE - Landkreis Peine",
				"PEG - Landkreis Bayreuth/Forchheim/Nürnberger Land",
				"PF - Stadt Pforzheim; Enzkreis",
				"PI - Kreis Pinneberg",
				"PIR - Landkreis Sächsische Schweiz-Osterzgebirge",
				"PL - Vogtlandkreis",
				"PLÖ - Kreis Plön",
				"PM - Landkreis Potsdam-Mittelmark",
				"PN - Saale-Orla-Kreis",
				"PR - Landkreis Prignitz",
				"PRÜ - Eifelkreis Bitburg-Prüm",
				"PS - Stadt Pirmasens; Landkreis Südwestpfalz",
				"PW - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
				"PZ - Landkreis Uckermark",
				"QFT - Saalekreis",
				"QLB - Landkreis Harz",
				"R - Stadt/Landkreis Regensburg; Polizeipräsidum Oberpfalz",
				"RA - Landkreis Rastatt",
				"RC - Vogtlandkreis",
				"RD - Kreis Rendsburg-Eckernförde",
				"RDG - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
				"RE - Kreis Recklinghausen",
				"REG - Landkreis Regen",
				"REH - Landkreis Hof/Wunsiedel im Fichtelgebirge",
				"REI - Landkreis Berchtesgadener Land",
				"RG - Landkreis Meißen",
				"RH - Landkreis Roth",
				"RI - Landkreis Schaumburg",
				"RID - Landkreis Kelheim",
				"RIE - Landkreis Meißen",
				"RL - Landkreis Mittelsachsen",
				"RM - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"RN - Landkreis Havelland",
				"RO - Stadt/Landkreis Rosenheim; Polizeipräsidum Oberbayern Süd",
				"ROD - Landkreis Cham/Schwandorf",
				"ROF - Landkreis Hersfeld-Rotenburg",
				"ROK - Donnersbergkreis",
				"ROL - Landkreis Kelheim/Landshut",
				"ROS - Landkreis Rostock",
				"ROT - Landkreis Ansbach",
				"ROW - Landkreis Rotenburg (Wümme)",
				"RP - Rhein-Pfalz-Kreis",
				"RPL - Rheinland-Pfalz, Landesregierung, Landtag, Polizei",
				"RS - Stadt Remscheid",
				"RSL - Stadt Dessau-Roßlau",
				"RT - Landkreis Reutlingen",
				"RU - Landkreis Saalfeld-Rudolstadt",
				"RÜD - Rheingau-Taunus-Kreis",
				"RÜG - Landkreis Vorpommern-Rügen",
				"RV - Landkreis Ravensburg",
				"RW - Landkreis Rottweil",
				"RZ - Kreis Herzogtum Lauenburg",
				"S - Stadt Stuttgart",
				"SAB - Landkreis Trier-Saarburg",
				"SAD - Landkreis Schwandorf",
				"SAL - Saarland, Landesregierung, Landtag, Polizei",
				"SAN - Landkreis Hof/Kronach/Kulmbach",
				"SAW - Altmarkkreis Salzwedel",
				"SB - Regionalverband Saarbrücken ohne die Stadt Völklingen",
				"SBG - Landkreis Vorpommern-Greifswald",
				"SBK - Salzlandkreis",
				"SC - Stadt Schwabach",
				"SCZ - Saale-Orla-Kreis",
				"SDH - Kyffhäuserkreis",
				"SDL - Landkreis Stendal",
				"SDT - Landkreis Uckermark",
				"SE - Kreis Segeberg",
				"SEB - Landkreis Sächsische Schweiz-Osterzgebirge",
				"SEE - Landkreis Märkisch-Oderland",
				"SEF - Landkreis Neustadt an der Aisch-Bad Windsheim",
				"SEL - Landkreis Wunsiedel im Fichtelgebirge",
				"SFB - Landkreis Oberspreewald-Lausitz",
				"SFT - Salzlandkreis",
				"SG - Stadt Solingen",
				"SGH - Landkreis Mansfeld-Südharz",
				"SH - Schleswig-Holstein, Landesregierung, Landtag, Polizei",
				"SHA - Landkreis Schwäbisch Hall",
				"SHG - Landkreis Schaumburg",
				"SHK - Saale-Holzland-Kreis",
				"SHL - Stadt Suhl",
				"SI - Kreis Siegen-Wittgenstein",
				"SIG - Landkreis Sigmaringen",
				"SIM - Rhein-Hunsrück-Kreis",
				"SK - Saalekreis",
				"SL - Kreis Schleswig-Flensburg",
				"SLE - Kreis Düren/Euskirchen",
				"SLF - Landkreis Saalfeld-Rudolstadt",
				"SLK - Salzlandkreis",
				"SLN - Landkreis Altenburger Land",
				"SLS - Landkreis Saarlouis",
				"SLÜ - Main-Kinzig-Kreis ohne die Stadt Hanau",
				"SLZ - Wartburgkreis",
				"SM - Landkreis Schmalkalden-Meiningen",
				"SMÜ - Landkreis Augsburg",
				"SN - Stadt Schwerin",
				"SO - Kreis Soest",
				"SOB - Landkreis Neuburg-Schrobenhausen",
				"SOG - Landkreis Weilheim-Schongau",
				"SOK - Saale-Orla-Kreis",
				"SÖM - Landkreis Sömmerda",
				"SON - Landkreis Sonneberg",
				"SP - Stadt Speyer",
				"SPB - Landkreis Spree-Neiße",
				"SPN - Landkreis Spree-Neiße",
				"SR - Landkreis Straubing-Bogen; Stadt Straubing; Polizeipräsidum Niederbayern",
				"SRB - Landkreis Märkisch-Oderland",
				"SRO - Saale-Holzland-Kreis",
				"ST - Kreis Steinfurt",
				"STA - Landkreis Starnberg",
				"STB - Landkreis Ludwigslust-Parchim",
				"STD - Landkreis Stade",
				"STE - Landkreis Lichtenfels",
				"STL - Erzgebirgskreis",
				"SU - Rhein-Sieg-Kreis",
				"SUL - Landkreis Amberg-Sulzbach",
				"SÜW - Landkreis Südliche Weinstraße",
				"SW - Stadt/Landkreis Schweinfurt",
				"SWA - Rheingau-Taunus-Kreis",
				"SZ - Stadt Salzgitter",
				"SZB - Erzgebirgskreis",
				"TBB - Main-Tauber-Kreis",
				"TDO - Landkreis Nordsachsen",
				"TE - Kreis Steinfurt",
				"TET - Landkreis Rostock",
				"TF - Landkreis Teltow-Fläming",
				"TG - Landkreis Nordsachsen",
				"THL - Thüringen, Landesregierung, Landtag",
				"THW - Bundesanstalt Technisches Hilfswerk",
				"TIR - Landkreis Tirschenreuth",
				"TO - Landkreis Nordsachsen",
				"TÖL - Landkreis Bad Tölz-Wolfratshausen",
				"TP - Landkreis Uckermark",
				"TR - Landkreis Trier-Saarburg; Stadt Trier",
				"TS - Landkreis Traunstein",
				"TÜ - Landkreis Tübingen",
				"TUT - Landkreis Tuttlingen",
				"UE - Landkreis Uelzen",
				"UEM - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
				"UFF - Landkreis Neustadt an der Aisch-Bad Windsheim",
				"UH - Unstrut-Hainich-Kreis",
				"UL - Stadt Ulm; Alb-Donau-Kreis",
				"UM - Landkreis Uckermark",
				"UN - Kreis Unna",
				"USI - Hochtaunuskreis",
				"V - Vogtlandkreis",
				"VAI - Landkreis Ludwigsburg",
				"VB - Vogelsbergkreis",
				"VEC - Landkreis Vechta",
				"VER - Landkreis Verden",
				"VG - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
				"VIB - Landkreis Landshut/Rottal-Inn",
				"VIE - Kreis Viersen",
				"VK - Stadt Völklingen",
				"VOH - Landkreis Neustadt an der Waldnaab",
				"VR - Landkreis Vorpommern-Rügen ohne die Stadt Stralsund",
				"VS - Schwarzwald-Baar-Kreis",
				"W - Stadt Wuppertal",
				"WA - Landkreis Waldeck-Frankenberg",
				"WAF - Kreis Warendorf",
				"WAK - Wartburgkreis",
				"WAN - Stadt Herne",
				"WAT - Stadt Bochum",
				"WB - Landkreis Wittenberg",
				"WBS - Landkreis Eichsfeld",
				"WDA - Landkreis Zwickau",
				"WE - Stadt Weimar",
				"WEL - Landkreis Limburg-Weilburg",
				"WEN - Stadt Weiden in der Oberpfalz",
				"WER - Landkreis Augsburg/Dillingen an der Donau",
				"WES - Kreis Wesel",
				"WF - Landkreis Wolfenbüttel",
				"WHV - Stadt Wilhelmshaven",
				"WI - Stadt Wiesbaden; Hessische Polizei",
				"WIL - Landkreis Bernkastel-Wittlich",
				"WIS - Landkreis Nordwestmecklenburg",
				"WIT - Ennepe-Ruhr-Kreis",
				"WIZ - Werra-Meißner-Kreis",
				"WK - Landkreis Ostprignitz-Ruppin",
				"WL - Landkreis Harburg",
				"WLG - Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald",
				"WM - Landkreis Weilheim-Schongau",
				"WMS - Landkreis Börde",
				"WN - Rems-Murr-Kreis",
				"WND - Landkreis St. Wendel",
				"WO - Stadt Worms",
				"WOB - Stadt Wolfsburg",
				"WOH - Landkreis Kassel",
				"WOL - Ortenaukreis",
				"WOR - Landkreis Bad Tölz-Wolfratshausen/München/Starnberg",
				"WOS - Landkreis Freyung-Grafenau",
				"WR - Landkreis Harz",
				"WRN - Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg",
				"WS - Landkreis Rosenheim",
				"WSF - Burgenlandkreis",
				"WST - Landkreis Ammerland",
				"WSW - Landkreis Görlitz",
				"WT - Landkreis Waldshut",
				"WTM - Landkreis Wittmund",
				"WÜ - Stadt/Landkreis Würzburg; Polizeipräsidum Unterfranken",
				"WUG - Landkreis Weißenburg-Gunzenhausen",
				"WÜM - Landkreis Cham",
				"WUN - Landkreis Wunsiedel im Fichtelgebirge",
				"WUR - Landkreis Leipzig",
				"WW - Westerwaldkreis",
				"WZ - Stadt Wetzlar",
				"WZL - Landkreis Börde",
				"X - Internationale Hauptquartiere (NATO)",
				"Y - Bundeswehr",
				"Z - Landkreis Zwickau",
				"ZE - Landkreis Anhalt-Bitterfeld",
				"ZEL - Landkreis Cochem-Zell",
				"ZI - Landkreis Görlitz",
				"ZIG - Schwalm-Eder-Kreis",
				"ZP - Erzgebirgskreis",
				"ZR - Landkreis Greiz",
				"ZW - Stadt Zweibrücken; Landkreis Südwestpfalz",
				"ZZ - Burgenlandkreis"
			],
			[
				"AG - Aargau",
				"AI - Appenzell Innerrhoden",
				"AR - Appenzell Ausserrhoden",
				"BE - Bern",
				"BL - Basel-Landschaft",
				"BS - Basel-Stadt",
				"FR - Fribourg",
				"GE - Geneva",
				"GL - Glarus",
				"GR - Graubünden",
				"JU - Jura",
				"LU - Lucerne",
				"NE - Neuchâtel",
				"NW - Nidwalden",
				"OW - Obwalden",
				"SG - St. Gallen",
				"SH - Schaffhausen",
				"SO - Solothurn",
				"SZ - Schwyz",
				"TG - Thurgau",
				"TI - Ticino",
				"UR - Uri",
				"VD - Vaud",
				"VS - Valais",
				"ZG - Zug",
				"ZH - Zürich"
			],
			[
				"01 - Ain/Bourg-en-Bresse/Auvergne-Rhône-Alpes",
				"02 - Aisne/Laon/Hauts-de-France",
				"03 - Allier/Moulins/Auvergne-Rhône-Alpes",
				"04 - Alpes-de-Haute-Provence/Digne-les-Bains/Provence-Alpes-Côte d'Azur",
				"05 - Hautes-Alpes/Gap/Provence-Alpes-Côte d'Azur",
				"06 - Alpes-Maritimes/Nice/Provence-Alpes-Côte d'Azur",
				"07 - Ardèche/Privas/Auvergne-Rhône-Alpes",
				"08 - Ardennes/Charleville-Mézières/Grand Est",
				"09 - Ariège/Foix/Occitanie",
				"10 - Aube/Troyes/Grand Est",
				"11 - Aude/Carcassonne/Occitanie",
				"12 - Aveyron/Rodez/Occitanie",
				"13 - Bouches-du-Rhône/Marseille/Provence-Alpes-Côte d'Azur",
				"14 - Calvados/Caen/Normandy",
				"15 - Cantal/Aurillac/Auvergne-Rhône-Alpes",
				"16 - Charente/Angoulême/Nouvelle-Aquitaine",
				"17 - Charente-Maritime/La/Rochelle/Nouvelle-Aquitaine",
				"18 - Cher/Bourges/Centre-Val de Loire",
				"19 - Corrèze/Tulle/Nouvelle-Aquitaine",
				"2A - Corse-du-Sud/Ajaccio/Corsica",
				"2B - Haute-Corse/Bastia/Corsica",
				"21 - Côte-d'Or/Dijon/Bourgogne-Franche-Comté",
				"22 - Côtes-d'Armor/Saint-Brieuc/Brittany",
				"23 - Creuse/Guéret/Nouvelle-Aquitaine",
				"24 - Dordogne/Périgueux/Nouvelle-Aquitaine",
				"25 - Doubs/Besançon/Bourgogne-Franche-Comté",
				"26 - Drôme/Valence/Auvergne-Rhône-Alpes",
				"27 - Eure/Évreux/Normandy",
				"28 - Eure-et-Loir/Chartres/Centre-Val de Loire",
				"29 - Finistère/Quimper/Brittany",
				"30 - Gard/Nîmes/Occitanie",
				"31 - Haute-Garonne/Toulouse/Occitanie",
				"32 - Gers/Auch/Occitanie",
				"33 - Gironde/Bordeaux/Nouvelle-Aquitaine",
				"34 - Hérault/Montpellier/Occitanie",
				"35 - Ille-et-Vilaine/Rennes/Brittany",
				"36 - Indre/Châteauroux/Centre-Val de Loire",
				"37 - Indre-et-Loire/Tours/Centre-Val de Loire",
				"38 - Isère/Grenoble/Auvergne-Rhône-Alpes",
				"39 - Jura/Lons-le-Saunier/Bourgogne-Franche-Comté",
				"40 - Landes/Mont-de-Marsan/Nouvelle-Aquitaine",
				"41 - Loir-et-Cher/Blois/Centre-Val de Loire",
				"42 - Loire/Saint-Étienne/Auvergne-Rhône-Alpes",
				"43 - Haute-Loire/Le/Puy-en-Velay/Auvergne-Rhône-Alpes",
				"44 - Loire-Atlantique 6/Nantes/Pays de la Loire",
				"45 - Loiret/Orléans/Centre-Val de Loire",
				"46 - Lot/Cahors/Occitanie",
				"47 - Lot-et-Garonne/Agen/Nouvelle-Aquitaine",
				"48 - Lozère/Mende/Occitanie",
				"49 - Maine-et-Loire/Angers/Pays de la Loire",
				"50 - Manche/Saint-Lô/Normandy",
				"51 - Marne/Châlons-en-Champagne/Grand Est",
				"52 - Haute-Marne/Chaumont/Grand Est",
				"53 - Mayenne/Laval/Pays de la Loire",
				"54 - Meurthe-et-Moselle/Nancy/Grand Est",
				"55 - Meuse/Bar-le-Duc/Grand Est",
				"56 - Morbihan/Vannes/Brittany",
				"57 - Moselle/Metz/Grand Est",
				"58 - Nièvre/Nevers/Bourgogne-Franche-Comté",
				"59 - Nord/Lille/Hauts-de-France",
				"60 - Oise/Beauvais/Hauts-de-France",
				"61 - Orne/Alençon/Normandy",
				"62 - Pas-de-Calais/Arras/Hauts-de-France",
				"63 - Puy-de-Dôme/Clermont-Ferrand/Auvergne-Rhône-Alpes",
				"64 - Pyrénées-Atlantiques 8/Pau/Nouvelle-Aquitaine",
				"65 - Hautes-Pyrénées/Tarbes/Occitanie",
				"66 - Pyrénées-Orientales/Perpignan/Occitanie",
				"67 - Bas-Rhin/Strasbourg/Grand Est",
				"68 - Haut-Rhin/Colmar/Grand Est",
				"69M - Metropolitan Lyon/Lyon/Auvergne-Rhône-Alpes",
				"69 - Rhône/Lyon (provisional)/Auvergne-Rhône-Alpes",
				"70 - Haute-Saône/Vesoul/Bourgogne-Franche-Comté",
				"71 - Saône-et-Loire/Mâcon/Bourgogne-Franche-Comté",
				"72 - Sarthe/Le Mans/Pays de la Loire",
				"73 - Savoie/Chambéry/Auvergne-Rhône-Alpes",
				"74 - Haute-Savoie/Annecy/Auvergne-Rhône-Alpes",
				"75 - Paris/Paris/Île-de-France",
				"76 - Seine-Maritime/Rouen/Normandy",
				"77 - Seine-et-Marne/Melun/Île-de-France",
				"78 - Yvelines/Versailles/Île-de-France",
				"79 - Deux-Sèvres/Niort/Nouvelle-Aquitaine",
				"80 - Somme/Amiens/Hauts-de-France",
				"81 - Tarn/Albi/Occitanie",
				"82 - Tarn-et-Garonne/Montauban/Occitanie",
				"83 - Var/Toulon/Provence-Alpes-Côte d'Azur",
				"84 - Vaucluse/Avignon/Provence-Alpes-Côte d'Azur",
				"85 - Vendée/La/Roche-sur-Yon/Pays de la Loire",
				"86 - Vienne/Poitiers/Nouvelle-Aquitaine",
				"87 - Haute-Vienne/Limoges/Nouvelle-Aquitaine",
				"88 - Vosges/Épinal/Grand Est",
				"89 - Yonne/Auxerre/Bourgogne-Franche-Comté",
				"90 - Territoire/de/Belfort/Belfort/Bourgogne-Franche-Comté",
				"91 - Essonne/Évry/Île-de-France",
				"92 - Hauts-de-Seine/Nanterre/Île-de-France",
				"93 - Seine-Saint-Denis/Bobigny/Île-de-France",
				"94 - Val-de-Marne/Créteil/Île-de-France",
				"95 - Val-d'Oise/Pontoise/Île-de-France",
				"971 - Guadeloupe/Basse-Terre/Guadeloupe",
				"972 - Martinique/Fort-de-France/Martinique",
				"973 - Guyane/Cayenne/French Guiana",
				"974 - La Réunion/Saint-Denis/Réunion",
				"976 - Mayotte/Mamoudzou/Mayotte",

			]
		]
